### ISSUE TITLE
Can't start mapping tools locally without plink files

### ISSUE THREAD

**Issue by mamarjan** [genenetwork/genenetwork2#100]
Lei, can you help me out? Is there a place I can download these files?

Thanks

**Comment by zsloan** [comment]
I just talked with Lei, and he is going to give you a link to the files. The file names contain the corresponding "group" name; for example, the CANDLE plink files correspond to "Child Development: CANDLE Cohort" group in GeneNetwork.

**Comment by lyan6** [comment]
I have sent you a link by an email.
