### ISSUE TITLE
GN2 Live: One database

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#104]
One database for GN1 and GN2

**Comment by pjotrp** [comment]
@lyan6 How are we doing on this one? Are we able to share one database now?

**Comment by lyan6** [comment]
Now the gn2-zach, gn2-lei, and gn2 (production) instances are all using the same database as the GN1 production server.

If everything is still running well after two weeks, we can go ahead and delete the database on penguin.

**Comment by pjotrp** [comment]
This is done, right? We can close then.

**Comment by lyan6** [comment]
Yes, done.
