### ISSUE TITLE
Searching for * takes a LONG time (and makes the server unresponsive)

### ISSUE THREAD

**Issue by DannyArends** [genenetwork/genenetwork2#115]
The search should be limited, currently if I can search for \* in the GetAny field, it takes a long time ( > 20 minutes) to run the search query. (I might have brought down the public version of gn2 by accident)

There are multiple solutions:
- When we query for results never allow more then 1000 results
- Do not allow wildcard only queries (such as \* or ????)

This is not critical, but might be easily abused / triggered, Any suggestions ?

**Comment by robwwilliams** [comment]
From Rob:  Or we can set up a separate Robots.gn2.genenetwork.org for
intense but rare queries. We do/did have a special instance of GeneNetwork
1 for robots.

On Wed, Sep 9, 2015 at 9:55 AM, Danny Arends <notifications@github.com>
wrote:

> The search should be limited, currently if I can search for * in the
> GetAny field, it takes a long time ( > 20 minutes) to run the search query.
> (I might have brought down the public version of gn2 by accident)
>
> There are multiple solutions:
>
>    - When we query for results never allow more then 1000 results
>    - Do not allow wildcard only queries (such as * or ????)
>
> This is not critical, but might be easily abused / triggered, Any
> suggestions ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/genenetwork/genenetwork2/issues/115>.
>



-- 
Rob

Robert W. Williams, Ph.D.
UT-ORNL Governor's Chair in Computational Genomics
Chair, Department of Genetics, Genomics and Informatics
University of Tennessee Health Science Center
Room 501
855 Monroe Avenue, Memphis TN 38163 USA

Office 901 448-7018  CELL 901 604 4752
Office: 501 Wittenborg Building
Department of Genetics: 71 Manassas St, Memphis TN 38163
EMAIL: rwilliams@uthsc.edu
Alternative email: labwilliams@gmail.com
SKYPE: robwwilliams

**Comment by DannyArends** [comment]
I think we can just limit the number of results, and dynamically page through the whole list.

We know how many results are being displayed on the first page of the web interface, so just get those and show them, the user should get the next 50 to 100 results when the user clicks to the next page, or scrolls down.

I put it on Github, so it's not forgotten.

**Comment by zsloan** [comment]
I remember that I was initially using pages when I first used DataTables
for the search results and we decided to just show all results instead. I'm
not sure why this is. Either way, it's a very easy change to make if we
decide to do it.

**Comment by robwwilliams** [comment]
In general we should show the whole set. This is the only way to
efficiently sort 2000 to 5000 hits. Has not been a problem for most
browsers up to 5000. After that size it does become slow.

On Wed, Sep 9, 2015 at 1:34 PM, zsloan <notifications@github.com> wrote:

> I remember that I was initially using pages when I first used DataTables
> for the search results and we decided to just show all results instead. I'm
> not sure why this is. Either way, it's a very easy change to make if we
> decide to do it.
>
> On Wed, Sep 9, 2015 at 11:55 AM, Danny Arends <notifications@github.com>
> wrote:
>
> > I think we can just limit the number of results, and dynamically page
> > through the whole list.
> >
> > We know how many results are being displayed on the first page of the web
> > interface, so just get those and show them, the user should get the next
> 50
> > to 100 results when the user clicks to the next page, or scrolls down.
> >
> > I put it on Github, so it's not forgotten.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/genenetwork/genenetwork2/issues/115#issuecomment-138973616
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/genenetwork/genenetwork2/issues/115#issuecomment-139000503>
> .
>



-- 
Rob

Robert W. Williams, Ph.D.
UT-ORNL Governor's Chair in Computational Genomics
Chair, Department of Genetics, Genomics and Informatics
University of Tennessee Health Science Center
Room 501
855 Monroe Avenue, Memphis TN 38163 USA

Office 901 448-7018  CELL 901 604 4752
Office: 501 Wittenborg Building
Department of Genetics: 71 Manassas St, Memphis TN 38163
EMAIL: rwilliams@uthsc.edu
Alternative email: labwilliams@gmail.com
SKYPE: robwwilliams

**Comment by zsloan** [comment]
What do you mean by it being easier to sort if it's all on one page? I
think the DataTables pages option will still sort through all samples, not
just the ones on the current page. Is it just that it's easier to scroll
through a bunch of things than it is to have to click through pages?

**Comment by robwwilliams** [comment]
Yes: Much easier to work with one large page, even if it is 5000 rows.

On Fri, Sep 11, 2015 at 10:33 AM, zsloan <notifications@github.com> wrote:

> What do you mean by it being easier to sort if it's all on one page? I
> think the DataTables pages option will still sort through all samples, not
> just the ones on the current page. Is it just that it's easier to scroll
> through a bunch of things than it is to have to click through pages?
>
> On Wed, Sep 9, 2015 at 5:46 PM, robwwilliams <notifications@github.com>
> wrote:
>
> > In general we should show the whole set. This is the only way to
> > efficiently sort 2000 to 5000 hits. Has not been a problem for most
> > browsers up to 5000. After that size it does become slow.
> >
> > On Wed, Sep 9, 2015 at 1:34 PM, zsloan <notifications@github.com> wrote:
> >
> > > I remember that I was initially using pages when I first used
> DataTables
> > > for the search results and we decided to just show all results instead.
> > I'm
> > > not sure why this is. Either way, it's a very easy change to make if we
> > > decide to do it.
> > >
> > > On Wed, Sep 9, 2015 at 11:55 AM, Danny Arends <
> notifications@github.com>
> > > wrote:
> > >
> > > > I think we can just limit the number of results, and dynamically page
> > > > through the whole list.
> > > >
> > > > We know how many results are being displayed on the first page of the
> > web
> > > > interface, so just get those and show them, the user should get the
> > next
> > > 50
> > > > to 100 results when the user clicks to the next page, or scrolls
> down.
> > > >
> > > > I put it on Github, so it's not forgotten.
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> >
> https://github.com/genenetwork/genenetwork2/issues/115#issuecomment-138973616
> > > >
> > > > .
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/genenetwork/genenetwork2/issues/115#issuecomment-139000503
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Rob
> >
> > Robert W. Williams, Ph.D.
> > UT-ORNL Governor's Chair in Computational Genomics
> > Chair, Department of Genetics, Genomics and Informatics
> > University of Tennessee Health Science Center
> > Room 501
> > 855 Monroe Avenue, Memphis TN 38163 USA
> >
> > Office 901 448-7018 CELL 901 604 4752
> > Office: 501 Wittenborg Building
> > Department of Genetics: 71 Manassas St, Memphis TN 38163
> > EMAIL: rwilliams@uthsc.edu
> > Alternative email: labwilliams@gmail.com
> > SKYPE: robwwilliams
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/genenetwork/genenetwork2/issues/115#issuecomment-139065402
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/genenetwork/genenetwork2/issues/115#issuecomment-139577177>
> .
>



-- 
Rob

Robert W. Williams, Ph.D.
UT-ORNL Governor's Chair in Computational Genomics
Chair, Department of Genetics, Genomics and Informatics
University of Tennessee Health Science Center
Room 501
855 Monroe Avenue, Memphis TN 38163 USA

Office 901 448-7018  CELL 901 604 4752
Office: 501 Wittenborg Building
Department of Genetics: 71 Manassas St, Memphis TN 38163
EMAIL: rwilliams@uthsc.edu
Alternative email: labwilliams@gmail.com
SKYPE: robwwilliams

**Comment by pjotrp** [comment]
This is an ongoing discussion. We are currently running the webserver on a single process. This is a *good* thing because it allows us to find the weak points. The '*'  search does not block the server - that is easy to test by opening a second tab in your browser. We do need to limit the response time for open queries and/or cache results. Easy to do when we have the REST server.

I am opening a new issue for the blocking server. Because that happens too.
