### ISSUE TITLE
WGCNA integration

### ISSUE THREAD

**Issue by DannyArends** [genenetwork/genenetwork2#119]
Creating an issue so we can put some idea's an discussion on Github 
My docker image is up2date (we needed an additional python package), New install script for R/qtl and WGCNA are found at: https://github.com/DannyArends/gn2-docker/blob/master/Renv_setup.R

I made an initial prototype for WGCNA in genenetwork2 (https://github.com/DannyArends/genenetwork2/tree/WGCNAintegration)
The current addition to genenetwork2:
 - Adds a button to the traits collection page
 - On press it loads WGCNA in the R environment
 - Displays an output message which traits were selected

Oww and please assign this issue to me..

**Comment by robwwilliams** [comment]
Danny: Great progress. Love to get your ideas about how to develop the
options and interfaces linking GN and WGCNA. Steve or Peter may be able to
help if we get snagged on any problems or if we just want advice on good
default parameters.

On Sat, Sep 19, 2015 at 12:40 PM, Danny Arends <notifications@github.com>
wrote:

> Creating an issue so we can put some idea's an discussion on Github
> My docker image is up2date (we needed an additional python package), New
> install script for R/qtl and WGCNA are found at:
> https://github.com/DannyArends/gn2-docker/blob/master/Renv_setup.R
>
> I made an initial prototype for WGCNA in genenetwork2 (
> https://github.com/DannyArends/genenetwork2/tree/WGCNAintegration)
> The current addition to genenetwork2:
>
>    - Adds a button to the traits collection page
>    - On press it loads WGCNA in the R environment
>    - Displays an output message which traits were selected
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/genenetwork/genenetwork2/issues/119>.
>



-- 
Rob

Robert W. Williams, Ph.D.
UT-ORNL Governor's Chair in Computational Genomics
Chair, Department of Genetics, Genomics and Informatics
University of Tennessee Health Science Center
Room 501
855 Monroe Avenue, Memphis TN 38163 USA

Office 901 448-7018  CELL 901 604 4752
Office: 501 Wittenborg Building
Department of Genetics: 71 Manassas St, Memphis TN 38163
EMAIL: rwilliams@uthsc.edu
Alternative email: labwilliams@gmail.com
SKYPE: robwwilliams

**Comment by DannyArends** [comment]
WGCNA update:

We can run the WGCNA analysis on a selected collection.

TODO'S:
- Setup the GN2 servers so that WGCNA is installed in R ( @lyan6 )
- Add the help texts found in the R-package to the different parameters / options ( @zsloan )
- Send the userdefined settings to R ( I will try n fix this before i pull request)
- WGCNA output page in such a way so that people can understand it
- The output page should provide options to do GO on the genes/traits found in Module X

Attach a draft of how the result page might look like (made using paint)

![wgcna output paintexample](https://cloud.githubusercontent.com/assets/47902/10334130/8e8bfcca-6ce8-11e5-9995-c265fbdef463.png)

**Comment by DannyArends** [comment]
Since screen shots are better then my MS paint thing...

I added / connected the WGCNA output for the soft thresholds table to the results page
Also now the gene <=> module table is created

![screenshot from 2015-10-07 15 09 27](https://cloud.githubusercontent.com/assets/47902/10338261/6ec079da-6d05-11e5-8513-2af6c5b08f87.png)

**Comment by DannyArends** [comment]
Again a little update:
Input from users is now used in the WGCNA analysis
- Users are now able to do dumb stuff (TODO: sanitize user input)

The output has been updated
- We also provide the module eigen-genes to the user ( TODO: Zach can you make it so that users can put them into their collection ?)
- Made it a little prettier (see screenshots) (TODO: Make it a LOT more pretty)

Anyway, I think we should start getting some user feedback

![screenshot from 2015-10-08 11 16 15](https://cloud.githubusercontent.com/assets/47902/10362326/4281cb2c-6dae-11e5-9ad2-812b56d5839d.png)
![screenshot from 2015-10-08 11 16 33](https://cloud.githubusercontent.com/assets/47902/10362327/452f9d54-6dae-11e5-8b95-e8cfacaca062.png)
![screenshot from 2015-10-08 11 18 25](https://cloud.githubusercontent.com/assets/47902/10362338/53b739f4-6dae-11e5-8819-75ab38626446.png)
