### ISSUE TITLE
Search results Download button doesn't work

### ISSUE THREAD

**Issue by zsloan** [genenetwork/genenetwork2#12]
_From @zsloan on May 5, 2015 18:8_

Nothing happens when the Download button is clicked; I don't think this was ever implemented.

_Copied from original issue: zsloan/genenetwork2#9_

**Comment by sn3twork** [comment]
http://stackoverflow.com/questions/14964035/how-to-export-javascript-array-info-to-csv-on-client-side

**Comment by sn3twork** [comment]
I notified @longlius about this issue, he's gonna fix it. I'm gonna work on something else.

**Comment by pjotrp** [comment]
I think this was fixed?

**Comment by zsloan** [comment]
Yes, this issue should be fixed for both regular and global search.

**Comment by pjotrp** [comment]
Thanks.
