### ISSUE TITLE
Genenetwork.org is blocked from Africa

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#133]
I noticed the same thing last year. The main website is not visible from Africa. The blocking happens 
at the firewall level. This is odd for an 'open' service. In the future it may not matter that much - with copies of GN sprouting up in more places.

**Comment by robwwilliams** [comment]
Costa Rica works fine.

On Sun, Dec 27, 2015 at 3:37 AM, Pjotr Prins <notifications@github.com>
wrote:

> I noticed the same thing last year. The main website is not visible from
> Africa. The blocking happens
> at the firewall level. This is odd for an 'open' service. In the future it
> may not matter that much - with copies of GN sprouting up in more places.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/genenetwork/genenetwork2/issues/133>.
>



-- 
Rob

Robert W. Williams, Ph.D.
UT-ORNL Governor's Chair in Computational Genomics
Chair, Department of Genetics, Genomics and Informatics
University of Tennessee Health Science Center
Room 501
855 Monroe Avenue, Memphis TN 38163 USA

Office 901 448-7018  CELL 901 604 4752
Office: 501 Wittenborg Building
Department of Genetics: 71 Manassas St, Memphis TN 38163
EMAIL: rwilliams@uthsc.edu
Alternative email: labwilliams@gmail.com
SKYPE: robwwilliams

**Comment by pjotrp** [comment]
It is a UTHSC thing. Also my vpn is blocked from Africa.

**Comment by robwwilliams** [comment]
Dear Lei,

Can you look at this problem this coming week?

On Thu, Dec 31, 2015 at 9:24 AM, Pjotr Prins <notifications@github.com>
wrote:

> It is a UTHSC thing. Also my vpn is blocked from Africa.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/genenetwork/genenetwork2/issues/133#issuecomment-168210869>
> .
>



-- 
Rob

Robert W. Williams, Ph.D.
UT-ORNL Governor's Chair in Computational Genomics
Chair, Department of Genetics, Genomics and Informatics
University of Tennessee Health Science Center
Room 501
855 Monroe Avenue, Memphis TN 38163 USA

Office 901 448-7018  CELL 901 604 4752
Office: 501 Wittenborg Building
Department of Genetics: 71 Manassas St, Memphis TN 38163
EMAIL: rwilliams@uthsc.edu
Alternative email: labwilliams@gmail.com
SKYPE: robwwilliams

**Comment by pjotrp** [comment]
I do have access from KEMRI. So, that is not blocked.

**Comment by pjotrp** [comment]
Now I am on a mobile network in Tanzania and I have access. Looks like something happened.

**Comment by pjotrp** [comment]
Maybe solved.
