### ISSUE TITLE
Git repo needs to go on a diet

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#134]
Related to https://github.com/genenetwork/genenetwork2/issues/15 the current git repo has to 
be reduced to core stuff. Data should go into a directory. Non GN2 modules should go into separate
git repositories. Splitting it all out will clarify things greatly to 'casual' readers and coders.

**Comment by zsloan** [comment]
The only issue with this (and it sounds like it's probably an acceptable one) is that GN2 won't work at all without those files; I think you'd get an error on the search result page when it builds the dataset and trait objects. But I guess that isn't as big of a deal as long as we make it clear that they also need all the genotype data files.

**Comment by pjotrp** [comment]
Yes. I don't expect GN2 to work without data and modules, but it is not something that is resolved by git. Large data files are part of an 'external' storage system.

In the source tree we expect only files that are coded by GN programmers. That way we keep it simple. Let's start by taking out the directories that are actually not needed by GN2 at this stage. Can you tell me which of these contains files that are not or no longer used in GN2? 
 
[dirlist.txt](https://github.com/genenetwork/genenetwork2/files/98718/dirlist.txt)

And which of wqflask/wqflask/static/packages/ do we actually use? I reckon these are external packages written by others and do not belong in our tree.

**Comment by zsloan** [comment]
I think there are quite a few directories that are not being used, mostly
being related to javascript (which includes the packages directory).
Tomorrow (or Monday if we're snowed out) I'll go through all directories
and remove what we're not using.

**Comment by pjotrp** [comment]
That would be great. Next phase I'll look into how to acquire these JS libraries in the cleanest way.

**Comment by zsloan** [comment]
Should I remove scripts that we aren't currently using but may use (or
borrow code from) in the future? Specifically, I'm looking at this
"load_genotypes_lei.py" file which looks like it's for leading stuff into
the database; since we currently just merge with the GN1 database we
haven't needed to use this code.

Also, should scripts that we *are* using (but aren't actually called when
GN2 is used) be included (for example, the scripts that generate/convert
genotype files)?

I'm assuming that I shouldn't include the former (the code will still be in
the git history anyways, right?), but I'm not sure if I should include the
latter or if those files should be in some other repo or something.

**Comment by pjotrp** [comment]
I think we should only have things in the repository we are actually using right now. Park the future stuff in another repo. We can reintroduce it when required.

The idea is to have a simple source base that everyone can understand. ;)

**Comment by pjotrp** [comment]
Scripts used for deployment can (arguably) remain in ./scripts or something.

**Comment by pjotrp** [comment]
New diet version exists.

**Comment by pjotrp** [comment]
Reopening since we reverted to the old tree. Now genotype files are removed it leaves just some of the JS libs. We have to revert at the same time (otherwise git history gets reintroduced). A job for this Memphis trip.

**Comment by pjotrp** [comment]
The tree is getting smaller thanks to removing code/libs. We'll attempt another diet on the git repo itself soon when we have merged Fred's python3 migration. Easy now it is only the three of us.

**Comment by pjotrp** [comment]
This is something to re-attempt in spring :)

**Comment by chfi** [comment]
Trello~~
