### ISSUE TITLE
Hard coded BXD.geno file in R/qtl caller

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#136]
https://github.com/genenetwork/genenetwork2/blob/master/wqflask/wqflask/marker_regression/marker_regression.py#L309

**Comment by pjotrp** [comment]
Should be plugged by genofilelocation var.

**Comment by zsloan** [comment]
Thanks for noticing that; when Danny was here and we were working on that,
we just wanted to get a test case working before he had to leave, and
apparently I forgot to ever go back and change it to accept a different
genotypes parameter. I'll fix this now.

**Comment by zsloan** [comment]
This should be fixed now.

**Comment by pjotrp** [comment]
Best to include the commit https://github.com/genenetwork/genenetwork2/commit/7f5536635ac20f7c670e4dc8e650f27d47503d78
