### ISSUE TITLE
Create reduced plant database

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#137]
@lyan6 @harmn @DannyArends We need a reduced database for the plant community. No need to have mouse and rat in there.

**Comment by pjotrp** [comment]
This should be a work in progress now.

**Comment by lyan6** [comment]
I am working on this.

**Comment by lyan6** [comment]
Finished.

Total size is 3.1GB now.

So where I can put this GN reduced plant database to?

**Comment by pjotrp** [comment]
Great! Make it available on Penguin or Penguin2 for me.

**Comment by lyan6** [comment]
I have put it into the MySQL on penguin.

The DB name is db_webqtl_plant_20160607.
