### ISSUE TITLE
Need to remove chdir when running GEMMA

### ISSUE THREAD

**Issue by zsloan** [genenetwork/genenetwork2#139]
Currently there's an os.chdir when running GEMMA, because it automatically creates the output directory wherever it is being run. We need to figure out some way around this.

**Comment by robwwilliams** [comment]
Dear Xiang,

Zach is working with an update of GN2 and may have some questions for you
about GEMMA.



On Thu, Feb 25, 2016 at 12:38 PM, zsloan <notifications@github.com> wrote:

> Currently there's an os.chdir when running GEMMA, because it automatically
> creates the output directory wherever it is being run. We need to figure
> out some way around this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/genenetwork/genenetwork2/issues/139>.
>



-- 
Rob

Robert W. Williams, Ph.D.
UT-ORNL Governor's Chair in Computational Genomics
Chair, Department of Genetics, Genomics and Informatics
University of Tennessee Health Science Center
Room 501
855 Monroe Avenue, Memphis TN 38163 USA

Office 901 448-7018  CELL 901 604 4752
Office: 501 Wittenborg Building
Department of Genetics: 71 Manassas St, Memphis TN 38163
EMAIL: rwilliams@uthsc.edu
Alternative email: labwilliams@gmail.com
SKYPE: robwwilliams

**Comment by robwwilliams** [comment]
Zach -- Please feel free to email me with any questions. We can also
schedule skype if needed.

Best,
Xiang

**Comment by zsloan** [comment]
Thanks, but I think we're okay for now. The only problem is that I couldn't
figure out how to change the directory where GEMMA generated the "output"
directory without using os.chdir, but Pjotr says he knows of a way so it
should be okay. The code itself runs fine, we just wanted to avoid using
os.chdir in the web server.
