### ISSUE TITLE
Set up external ports for development

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#146]
Pjotr needs three ports that can be used for GN2 Guix instances.

**Comment by lyan6** [comment]
"Three ports" means three network ports by firewall? Or three GN2 instances?

**Comment by pjotrp** [comment]
Three domain names is fine: pjotr-gn2., test-gn2. and guix.genenetwork.org will work. Can you open both ports 80 and 443 on these?

**Comment by lyan6** [comment]
The three domain names:
guix.genenetwork.org
pjotr-gn2.genenetwork.org
test-gn2.genenetwork.org

point to:
penguin2.uthsc.edu
128.169.4.44

**Comment by lyan6** [comment]
The following ports for Server Penguin AND Server Penguin2 are opened:

80 (TCP, HTTP), open to campus inside AND outside.
443 (TCP, HTTPS), open to campus inside AND outside.
8080 (TCP, HTTP), open to campus inside AND outside.

**Comment by pjotrp** [comment]
8080 not working.

**Comment by pjotrp** [comment]
We are running test-gn2.genenetwork.org now on port 80 using nginx on P2.
