### ISSUE TITLE
Large files need to be stored in shared directory

### ISSUE THREAD

**Issue by zsloan** [genenetwork/genenetwork2#15]
_From @pjotrp on May 5, 2015 21:18_

The idea is to have a shared storage for a server. E.g.

STORAGE=/export/local/gn2/storage

This can be set in the configuration for every running server. Within the storage dir we'll use MD5 values (of the contained files) to uniquely set the dirname, e.g.

/export/local/gn2/storage/d849b0238cd26434237b28498628837d/files...

That hash value will be used to locate the data.

_Copied from original issue: zsloan/genenetwork2#13_

**Comment by pjotrp** [comment]
@zsloan There is a dir named wqflask/output. I think we can safely remove that, correct? Please don't remove it from your tree - I'll do the actual removals in the diet tree.

**Comment by zsloan** [comment]
Yeah, it was already removed from my tree apparently, but I didn't notice
it was in the .gitignore file so it was never removed when I pulled to
production.

I won't do anything, but remember to remove the reference to the path in
.gitignore.

**Comment by pjotrp** [comment]
Large files have moved into a static directory.
