### ISSUE TITLE
Add gemma testing database into GN db

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#151]
For development we want to be able to run a small dataset with plink. We'll try to add the data that comes with gemma, so we use the same test set.

**Comment by robwwilliams** [comment]
Great idea. The best small test set we have now is the Human Liver
Consortium data.


On Fri, Mar 18, 2016 at 3:02 PM, Pjotr Prins <notifications@github.com>
wrote:

> For development we want to be able to run a small dataset with plink.
> We'll try to add the data that comes with gemma, so we use the same test
> set.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/genenetwork/genenetwork2/issues/151>
>



-- 
Rob

Robert W. Williams, Ph.D.
UT-ORNL Governor's Chair in Computational Genomics
Chair, Department of Genetics, Genomics and Informatics
University of Tennessee Health Science Center
Room 501
855 Monroe Avenue, Memphis TN 38163 USA

Office 901 448-7018  CELL 901 604 4752
Office: 501 Wittenborg Building
Department of Genetics: 71 Manassas St, Memphis TN 38163
EMAIL: rwilliams@uthsc.edu
Alternative email: labwilliams@gmail.com
SKYPE: robwwilliams
