### ISSUE TITLE
Database URLs not working on trait page

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#153]
When on a trait page, e.g.,

  http://gn2.genenetwork.org/show_trait?trait_id=1435395_s_at&dataset=HC_M2_0606_P#redirect

the database link for 'Hippocampus Consortium M430v2 (Jun06) PDNN' is not working:

  http://gn2.genenetwork.org/static/dbdoc/Hippocampus%20Consortium%20M430v2%20%28Jun06%29%20PDNN.html

The page exists in GN1 as 

  http://www.genenetwork.org/dbdoc/HC_M2_0606_P.html

We could point at GN1 for the time being...

**Comment by zsloan** [comment]
Fixed this in commit b7cabb198f7d3c47074da3e6d0d523281aad7e13
