### ISSUE TITLE
Glossary URL is not working on trait page

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#154]
http://gn2.genenetwork.org/glossary.html#normal_probability

For now we could point at GN1's

http://www.genenetwork.org/glossary.html#normal_probability

**Comment by pjotrp** [comment]
More links not working on trait page (I am testing on http://gn2.genenetwork.org)

http://gn2.genenetwork.org/glossary.html#Correlations
http://gn2.genenetwork.org/correlationAnnotation.html#sample_r
https://en.wikipedia.org/correlationAnnotation.html
https://grits.eecs.utk.edu/webqtl/main.py?FormID=tissueCorrelation
/webqtl/main.py?FormID=tissueCorrelation

**Comment by zsloan** [comment]
These links should be fixed now (along with some related javascript) and I also removed target="_blank" from them.
