### ISSUE TITLE
Winsorizing suggested, but misses instruction of doing it in GN2 -  need to add winsorizing

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#158]
On the trait page outliers suggest winsorizing. But I can't find the button to do that.

**Comment by zsloan** [comment]
This feature doesn't exist yet so I removed that part of the text until we implement it.

**Comment by pjotrp** [comment]
I think we need it. Bumped priority.

**Comment by pjotrp** [comment]
We have outlier detection - but still lack removing them. @zsloan this is reasonably important for going live.

**Comment by pjotrp** [comment]
We won't add winsorizing, but something more sophisticated (later).
