### ISSUE TITLE
Server bombs out on correlation of

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#169]
http://gn2.genenetwork.org/show_trait?trait_id=1433387_at&dataset=HC_M2_0606_P

SQL syntax problem. I can replicate this on all instances of GN2.

Traceback (most recent call last):

  File "/home/gn2/gene/wqflask/base/mrna_assay_tissue_data.py", line 103, in get_symbol_values_pairs
    results = g.db.execute(query).fetchall()

ProgrammingError: (_mysql_exceptions.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') and\n                         TissueProbeSetXRef.DataId = TissueProbeSetData.Id' at line 3") [SQL: 'SELECT TissueProbeSetXRef.Symbol, TissueProbeSetData.value\n                   FROM TissueProbeSetXRef, TissueProbeSetData\n                   WHERE TissueProbeSetData.Id IN (  ) and\n                         TissueProbeSetXRef.DataId = TissueProbeSetData.Id']

**Comment by zsloan** [comment]
This should be fixed now. Some datasets do not seem to have data_ids, so I just had it skip tissue correlations in those cases.
