### ISSUE TITLE
Marker regression error on 'interval mapping'

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#175]
Loading the temp CSV works fine with pylmm and R/qtl. Interval mapping, however, gives the following error (use the gn-staging branch)

  File "/export2/izip/git/opensource/genenetwork/sumo_gn2/wqflask/wqflask/views.py", line 484, in marker_regression_page
    writer.writerow((row["name"], row["chr"], row["Mb"], row["lod_score"]))
KeyError: 'lod_score'

**Comment by zsloan** [comment]
I can fix this, shouldn't be too hard. I'll look at it tomorrow morning.

**Comment by chfi** [comment]
I've fixed it - interval mapping used another key, so added a check for that.
https://github.com/chfi/genenetwork2/commit/6d2a5d91c83413f470fec1f76f197c7f7a2ed654#diff-1da05a30ee250ec1a8a07b3fe2989c75L484

**Comment by pjotrp** [comment]
Thanks!
