### ISSUE TITLE
Remove python-pil and python-piddle dependencies

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#176]
Some figures use piddle and pil. These are unmaintained Python2 modules and will be phased out.

**Comment by pjotrp** [comment]
They can be replaced with python-pillow

**Comment by pjotrp** [comment]
This makes interesting reading: http://www.economist.com/news/business/21704842-why-big-firms-delta-find-it-so-hard-eliminate-glitches-their-it-systems-all-systems

It is an option to have the images drawn by an external program.

**Comment by zsloan** [comment]
I remember looking at this when first porting the GN1 mapping code, and it isn't a straight-forward upgrade. I'm looking at it again right now and have run into a problem with the way they deal with fonts. 

With piddle, if you use pid.Font(ttf="fontname", size=the_size) it will automatically search in the truetypefont directory of the piddle directory for the font in question. Pillow uses ImageFont.truetype("somefont.ttf", the_size), and it isn't clear where it looks for the font files. The documentation says where it looks in _Windows_, but not Ubuntu/Linux, and putting the font directory in the Pillow installation directory doesn't seem to work.

**Comment by pjotrp** [comment]
Pillow deployed with PIL gives conflicts, such as 

```
    GeneNetwork penguin2:sumo_gn2:2.10rc3-testing-d86f07f61 http://pjotr-gn2.genenetwork.org/marker_regression ( 8:05AM UTC Aug 24, 2017)
    setink() has been removed. Please use keyword arguments instead. (error)
      File "/usr/local/guix-profiles/gn2-2.10rc4/lib/python2.7/site-packages/PIL/ImageDraw.py", line 92, in setink
        "Please use keyword arguments instead.")
```

**Comment by pjotrp** [comment]
The later Pillow uses the same name space as
the older PIL which we are using. You can see the mixture in

    ls /usr/local/guix-profiles/gn2-2.10rc4/lib/python2.7/site-packages/PIL/ -l

it contains files from both modules and Pillow overwrites the old ones
:/

We need both modules since other libraries now use Pillow.

I think the way forward it to put the old PIL in its own namespace. We
are using our own cached tarball anyway. It means we'll have to modify
some references in the GN2 source code. It would remove the issue.

In time we should move to the new Pillow.

**Comment by pjotrp** [comment]
I moved PIL into the PIL1 name space. Now it no longer interferes with pillow. Sources are at http://files.genenetwork.org/software/contrib/

**Comment by pjotrp** [comment]
See #289

**Comment by fredmanglis** [comment]
@pjotrp I've looked at the definition of genenetwork2 in [guix-bioinformatics](https://gitlab.com/genenetwork/guix-bioinformatics.git) (branch `master`), and it does seem like the `python2-piddle-gn` and `python2-pil1` dependencies are commented out already, meaning they are no longer part of the dependency graph.

I've deleted the commented out sections for cleanliness, but there does not seem to be much to do here. Please verify and close this.

**Comment by pjotrp** [comment]
Yes, they have been removed in my branch.
