### ISSUE TITLE
Consistency regarding JS libraries

### ISSUE THREAD

**Issue by zsloan** [genenetwork/genenetwork2#18]
_From @lomereiter on May 6, 2015 10:26_

`jQuery` and `D3.js` are fetched from external websites, while most other libraries are stored locally

Estimated time/difficulty: Easy

_Copied from original issue: zsloan/genenetwork2#17_

**Comment by pjotrp** [comment]
Needs to be running from the same webserver. Don't add the libraries to the git tree.

**Comment by pjotrp** [comment]
Duplicate of #135
