### ISSUE TITLE
MySQL error

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#182]
Because of https://github.com/genenetwork/genenetwork2/commit/d8789ca07d2cce3a89edca39000a8e5d3def7e6c I am getting

ProgrammingError: (_mysql_exceptions.ProgrammingError) (1146, "Table 'db_webqtl_s.Geno
File' doesn't exist") [SQL: "\n        SELECT GenoFile.`location`,GenoFile.`title`\n
      FROM GenoFile\n        WHERE GenoFile.`server`='localhost'\n        AND GenoFile
.`InbredSetID`='1'\n        ORDER BY GenoFile.`sort`\n        "]

We should always have a sane default!!

Also selecting genotypes by server name is, erm, questionable.

**Comment by pjotrp** [comment]
The geno location should not be stored in the SQL database. It is, actually, already part of the settings file in ./etc/default_settings.py. The *default* is GENENETWORK_FILES = HOME+"/gn2_data", but that can be changed to point to some other dir.

I am happy the files are no longer stored in the main gn2 source tree! But please use the GENENETWORK_FILES variable to locate data files on a local server.

**Comment by pjotrp** [comment]
Furthermore, all public geno files will be downloadable from files.genenetwork.org - I have a small subsample there that currently gets installed by Guix.

**Comment by lyan6** [comment]
I think these are some reasons:

In the first, GN1 and GN2 support multiple geno files for each Group (InbredSet).

1.From that error message, look like it is using db “db_webqtl_s”, not “db_webqtl”, I think “db_webqtl_s” is not updated.
2.GN1 and GN2 are sharing one db now, so on different servers geno files are different for some points.
3.https://github.com/genenetwork/genenetwork2/blob/master/wqflask/wqflask/show_trait/show_trait.py
We are using “GENENETWORK_FILES” variable in setting files.

But if you think it is better, I can move all the geno file location info into setting file.

**Comment by pjotrp** [comment]
Yes, please use the setting file. That is used for server specific settings. We will have many different databases in the future, so we can not assume they 'know' about the server they are running on.

**Comment by lyan6** [comment]
Fixed in my branch.

https://github.com/lyan6/genenetwork2/commit/df543ff395dd3c92b9cb4d45c7c8eac66abb7b76
https://github.com/lyan6/genenetwork2/commit/820a4c5657890bd8352c101d7c08fc7b50519255

**Comment by pjotrp** [comment]
Thanks for fixing! The webserver can be run again on my database.

We need one more improvement. All global settings are listed in ./etc/default_settings.py AND wqflask/utility/tools.py.  Now I think we should have one dir containing all static files on a server (geno and pheno), which is pointed at by GENENETWORK_FILES.  Therefore your GENOFILES should be a subdirectory of this variable. Now in wqflask/base/webqtlConfig.py we set derived vars, such as

```python
GENODIR              = flat_files('genotype')+'/'
```

i.e. GENODIR is GENETWORK_FILES+'/genotype'. I propose all genotype files are hosted there, rather than introducing a new directory and variable. What do you think?

So replace your GENOFILES  with GENODIR. They are really the same thing (besides FILES is less accurate than DIR).

**Comment by pjotrp** [comment]
With https://github.com/genenetwork/genenetwork2/commit/e4df1a6d05c1fe7ee2ebaa90bc796801ebd4934c I have disabled the loading of genofiles in master. Please follow the suggestions in the source.
