### ISSUE TITLE
What to do with qtlreaper (and a note on longer running computations)

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#183]
Qtlreaper corrupts memory with the latest large genotype files. As it is linked against Python, this breaks and stops the webserver - something that is not acceptable. I had a peek in the 2005 code and qtlreaper does memory allocations which overflow. Also it includes ancient versions of linalg libs.

Looking at the gn2 code it is just used in a few places. Namely for reading .geno files (which bomb out now), for correlations, for mapping and for some basic statistics. All of which can be done by other tools. Rather than fixing qtlreaper I propose we replace it - or it is going to give us more grief later.

In general, I also want to discourage linking algorithms into the webserver - as is done with R/qtl through Rpy2 etc. Each of these libs can *break* the webserver and we can not control all edge cases. 

Algorithms should run in separate processes, as we do with pylmm, so that if something goes wrong the service can continue (with an error message). It will also make it much easier to farm out these computations to other servers (as will be done with pylmm).

The principle is: any long running computation (i.e., larger than one second) should be in a separate process.

**Comment by zsloan** [comment]
It seems like the memory issue also occurs using pyLMM and R/qtl with the
new genotypes, not just qtlreaper?

**Comment by zsloan** [comment]
One other thing regarding running the other methods from the command line
like with PYLMM - I'm assuming this means they would also need to store the
results in Redis?

**Comment by pjotrp** [comment]
I now realise Reaper is also doing the interval mapping. So we can't drop it for IM. But we *can* drop it for reading the geno files - that is the one that crashes all mappers.

Regarding processes and redis: we will drop redis for gn_server. Don't change the way RPy2 is called now - we'll change it later.

**Comment by pjotrp** [comment]
I added a number of patches to QTLreaper, including https://github.com/pjotrp/QTLReaper/commit/363a93fe49daa8afca6b5987640f635f3aeb36e7, which checks for memory boundaries. Now, at least we should get errors on overflow which will make finding the problems easier.

Also, this way, we may have gotten rid of one cause of random server hangs and crashes.
