### ISSUE TITLE
Change git(hub) policy of having everyone write to GN2 master branch

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#184]
My proposal is to have only one person handle the main repo - this person is responsible for integration of other people's code. With an increasing number of people commiting the chances of failing integration increases (i.e., the master branch is currently broken for my database because of https://github.com/genenetwork/genenetwork2/issues/182, and it is still not fixed after 24 hrs).

The new policy is in line with how git is normally used.

**Comment by leiyan** [comment]
No problem for me. Thanks.

**Comment by pjotrp** [comment]
Policy in use now.
