### ISSUE TITLE
Move genofiles to separate dir

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#187]
We are moving genotype files out of the source code repository into a dir pointed at by GENENETWORK_FILES (i.e., the GENODIR). The actual files will be downloadable from http://files.genenetwork.org/

**Comment by pjotrp** [comment]
This is in master. Still need to add it to Guix.

**Comment by zsloan** [comment]
Since the genofiles have already been moved to a new directory outside of the git repository, I think this issue can be closed.
