### ISSUE TITLE
List collections does not allow to select when not logged in

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#197]
http://test-gn2.genenetwork.org/collections/list

Not sure what the behaviour is when logged in...

**Comment by zsloan** [comment]
This seems to be working for me when not logged in (assuming you're talking
about selecting a collection from the list). I guess it's just an issue
with your version for some reason?

Have you been able to test or use any other collection functionality?

**Comment by pjotrp** [comment]
This is the master branch! Try above URL.

**Comment by zsloan** [comment]
Did you fix this, because it seems to be working? Maybe the issue is with
the specific traits you're adding?

**Comment by pjotrp** [comment]
Remember I am not logged in. Wipe the relevant cookies in your browser.

**Comment by zsloan** [comment]
I recently fixed the issue I mentioned in my above comment. I can't seem to find any remaining issues, but I'll leave this issue open just in case.
