### ISSUE TITLE
Autocompletion in search fields

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#204]
This is a mechanism we can use for (caching) autocompletion of search fields:
https://www.sitepoint.com/jquery-ajax-html5-datalist-autocomplete/

It uses an HTML5 indexed database stored locally in the browser. This sets limits to the number of elements we want to store, but at least we only have to transmit once. 

I am thinking we should autocomplete trait names (but not all the at ones), gene names, experiment names, species and individuals. That would amount to a few 100K names max. What more?

**Comment by zsloan** [comment]
Maybe datasets also, since there's a relatively small number of those and
someone might search for them using global search.
