### ISSUE TITLE
Genotype selector

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#209]
For those case that we have multiple genotypes we would like to add a
selector.

Rather than storing that data in the database I prefer to store it as
metadata with the genotype files. I.e., the genotype directory is the
place to store this information.

For BXD, for example, we would like to make it selectable to have
multiple .geno files. So how about creating a JSON file named
genotype_meta.json that sits in $GENENEWORK_FILES/genotypes/? It can
contain the information that we seek.

The reason to _not_ store it in the database is that we'll have
different databases and different genotype directories and
combinations thereof. There is no good way to keep these
synchronized. One deployment may want BXD17K, another may just use
BXD. It is a deployment thing.

So best keep the metadata where the data is.

Also, when no genotype options are available, we don't want to show
the dropdown selector.

**Comment by zsloan** [comment]
So I'm guessing we should we write a script that will generate this JSON
using the contents of the database?

**Comment by zsloan** [comment]
Wait nevermind that doesn't make sense, for some reason I was thinking of
the information about genofiles being in the database.

So we would just leave it to people to create their own version of the
metafile by hand then?

**Comment by pjotrp** [comment]
Yes. Basically it is metadata that tells you that you can use two different BXD genotype files and we generate the menu selector from that information. Earlier that metadata was in the DB, but I don't think it belongs there. This metadata is an exension of deployment settings.

**Comment by lyan6** [comment]
A good online JSON tool, I am using it:
http://www.jsoneditoronline.org/

**Comment by lyan6** [comment]
What do you think about this json file?

{
  "BXD": [
    {
      "title": "Classic Genotypes (2001-2016)",
      "location": "BXD.geno"
    },
    {
      "title": "New Genotypes (2017)",
      "location": "BXD.4.geno"
    }
  ]
}

**Comment by pjotrp** [comment]
Yes, that is the idea

**Comment by pjotrp** [comment]
How is it going?

**Comment by lyan6** [comment]
I hope I can finish it tomorrow.

**Comment by lyan6** [comment]
I am using "simplejson" to parse json files, so simplejson object cannot be used in jinja2 directly? Right?

**Comment by pjotrp** [comment]
Why not use standard 'import json' ?

**Comment by lyan6** [comment]
I figured it out, thanks.
I will send PR tomorrow.

**Comment by zsloan** [comment]
To be honest, I'm not sure. We had been using that at some point in the
past (I think maybe the consultant we used to work used it?), and I assumed
it was best to not make any unnecessary changes.

I found this explanation about the difference between simplejson and json
online:

json is simplejson, added to the stdlib. But since json was added in 2.6,
> simplejson has the advantage of working on more Python versions (2.4+).
> simplejson is also updated more frequently than Python, so if you need (or
> want) the latest version, it's best to use simplejson itself, if possible.


 It is possible that it might have something to do with the "working on
more Python versions" thing (since I think GN1 might be 2.4), though I
think GN2 has always been 2.7.

Either way it probably isn't necessary but also doesn't seem to be
considered strange or wrong, so I don't mind if you want to remove it.

**Comment by pjotrp** [comment]
Acutally simplejson is also part of Guix. So if you use staging it should just work.

**Comment by pjotrp** [comment]
Merged. Some small changes for spacing and using the GENODIR directory for the meta file, see https://github.com/genenetwork/genenetwork2/commit/b1a255c0990641fb4b4b8682eae3589bf0d3abb3

One more task is to show the .geno file used in the results page of the mapping.

**Comment by zsloan** [comment]
The thing Pjotr mentioned in the most recent comment was actually mentioned in a separate issue, and I've already made the change to show the genofile name on my branch (which will be included in next push).

So I guess it's fine to close this now.
