### ISSUE TITLE
Replace settings.py file with JSON overrides

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#218]
Overrides will simplify deployment - so we don't have to copy all settings every time - which is error prone and may change between versions of GN2.

**Comment by zsloan** [comment]
What exactly do you mean by JSON overrides?

**Comment by pjotrp** [comment]
See https://github.com/genenetwork/deploy/blob/master/doc/gn2_on_penguin.org#configuring-gn2

**Comment by pjotrp** [comment]
Dropped this in favour of environment variables.
