### ISSUE TITLE
On parameter error the mapping jumps to the correlation output page

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#223]
We should show an error by default, rather than unexpected behaviour.

**Comment by pjotrp** [comment]
Jquery says: Error: Syntax error, unrecognized expression: input[name=genofile

Looks like it has to do with the recent genotype selector.

**Comment by zsloan** [comment]
Maybe it's just that the genofile selector is the first non-correlations
parameter it comes across (since it's the first one that appears after the
correlations options).

**Comment by zsloan** [comment]
This was changed to not default to corr_compute, and both correlation and mapping are now sent to loading page first.
