### ISSUE TITLE
Correlation computation error: GTEXv5 Human Lung RefSeq (Sep15) RPKM log2

### ISSUE THREAD

**Issue by robwwilliams** [genenetwork/genenetwork2#233]
Zach: If you compute the top 500 correlates (Pearson) in GN1 and GN2 for the gene APOL1, the returned set of genes/transcripts if quite difference. GN1 finds ONLY covariates with N = 335 values and the  absolute value of the maximum correlations is 0.769 (LAP3). GN2 finds covariates with only N = 6 and maximum correlations of 0.989 to GIP.  The GN1 behavior is probably correct. I can show this to you tomorrow.

**Comment by robwwilliams** [comment]
Another correlation problem using BXD spleen data and traits

Zcchc24 (10418171)	versus 	Itpr3 (10443131)

 GeneNetwork v2.10-pre1-testing-e6528ba52 http://test-gn2.genenetwork.org/corr_matrix ( 2:40PM UTC Nov 11, 2016)
    Index out of range. (error)
      File "/usr/local/guix-profiles/gn2-staging/lib/python2.7/site-packages/rpy2-2.7.6-py2.7-linux-x86_64.egg/rpy2/robjects/vectors.py", line 253, in __getitem__
        res = super(Vector, self).__getitem__(i)

**Comment by pjotrp** [comment]
@zsloan is this fixed?

**Comment by zsloan** [comment]
This issue still exists, though I'm not sure if it's the exact same problem that was originally described. The actual correlations are the same (if you look at the same gene in the results it will have the same r), but the list is different and doesn't include most of the higher correlated genes from the GN1 results.

The issue with N Rob described doesn't seem to be the case (anymore at least). I'll see if I can figure out what's causing the issue.

**Comment by zsloan** [comment]
So it seems that this issue was caused by NaN's messing up the sort. I changed the logic to ignore results with NaN for sample_r, and this fixed the issue.
