### ISSUE TITLE
MySQL times out if GN2 isn't used for some amount of time

### ISSUE THREAD

**Issue by zsloan** [genenetwork/genenetwork2#236]
Whenever GN2 is accessed in a way that requires querying the database after it hasn't been used for a while (maybe 12+ hours) it will throw an error. Reloading the page will then work fine. I'm not sure what the cause of this error is, but it might be because db_session (which is defined in wqflask/wqflask/database.py) is never closed. There is one function, shutdown_session in views.py, which closes db_session, and it is never called anywhere. I'm not sure where to close it, though; I tried closing it after every time it was used in user_manager.py, but this caused some errors.

**Comment by pjotrp** [comment]
Does this still happen? Reopen if it does.
