### ISSUE TITLE
PYLMM results strange for some traits

### ISSUE THREAD

**Issue by zsloan** [genenetwork/genenetwork2#250]
Example trait - http://gn2-zach.genenetwork.org/show_trait?trait_id=12661&dataset=BXDPublish

The results are significantly different between PYLMM and R/qtl (with R/qtl showing results that are closer to what you'd expect). While hiding outliers helps a little bit, there's still a whole new peak that shouldn't exist in the PYLMM output.

**Comment by pjotrp** [comment]
We are going to try a different LMM soon. I am waiting for that to see if it solves this problem.
