### ISSUE TITLE
Basic Statistics: Or why I still have not switched from GN1 to GN2 (GUI issues)

### ISSUE THREAD

**Issue by robwwilliams** [genenetwork/genenetwork2#252]
# **GUI improvements needed for Statistics tabs**

Already looking really good. Better on average than GN1, but lots of room for minor improvements. Here they are. 

Zach or Lei or anyone else: please have at this list:

**"Trait Data and Analysis" pages in GN2
Second bar "Statistics"**

## Tab 1:  "Basic Statistics" 
1. First column is too wide. Reduce to 1.3X what is needed by text.
2. No blue text for "Interquartile Range" even though this is a link. WHY?  Because this table needs to be publication-ready and needs to be in great shape for inclusion in reports and presentations.
3. Value column is incorrectly justified for numbers. Should be either right justified or decimal justified.

4. Range data for all traits, including Phenotypes.  This is a bit hard due to the scale of measurement. In our MySQL table "ProbeSeetFreeze" we have a field "DataScale" that we use to determine how to calculate range correctly in GN1 but not in GN2. We need to generalize this "DataScale" field for ALL DATA in all tables in GN2 (make it better than GN1). Data can be log2, log10, ratio, fractional, percentage, ordinal, dichotomous, positive only, negative and positive, Z scores, other. Understanding the data scale and range is critical to us and for longterm success. 

**Rob would be happy to curate the data scale metadata but I will need a web tool and simple interface.**

5.  Every table and graph needs to list the trait somewhere (top usually, but bottom is ok). WHY?  Because these les and tabgraphs will be used free-standing in presentations. They way we handle this is "Correlation Scatter Plots" is good.

## Tab 2: Histogram (this is a cool new feature not seen in GN1, hurray)

1. We are still plagued by the vertical white line inconsistency problem.  Love to see this fixed once and for all
![screen shot 2017-03-16 at 5 23 18 pm](https://cloud.githubusercontent.com/assets/12311292/24021140/5e5b4744-0a6d-11e7-95af-a04b728e345e.png)

1b. Get rid of the column count in the bars. This fails when the count gets up to three digits 

![screen shot 2017-03-16 at 6 31 15 pm](https://cloud.githubusercontent.com/assets/12311292/24022849/cfcc7ea8-0a76-11e7-9e50-d7646afdcecc.png)

If you want to add thin horizontal lines at the Y axis tick marks that is ok with me (like in Bar Chart)

2. The X axis has to be "written" last so that the width is uniform. Right now the bars "erase" one pixel of the X axis. Looks weird.

2. Numbers on the X and Y axis need to be larger or bold. Also may need to  control for very large numbers on these axes in smart ways (check some of the BXD Liver Metabolome data).

3. Could the user help control the number of bars using a "More" or "Less"  or "Default"

4. Graph needs to list the trait somewhere (top usually, but bottom is ok). 

## Tab 3: Bar Chart.  Looks good but not quite perfect yet.

1. Numbers on X and Y axis are too small and too close to the line. How are large numbers handled on the Y axis. Check using BXD Liver Metabolome.

Bars looks great for traits with between 10 and 100 cases.  From 100 to 200 they are just barely ok. Above 200 they get silly. X axis is just too long.
 
See this example:
http://gn2.genenetwork.org/show_trait?trait_id=100160455_TGI_at&dataset=GSE23546HLT0613

2. What do we do when we have >200?  
Two options: 
A. Could just skip the histogram when N >199 
B. Replace with probability density plot. This will be similar to histogram but slightly more sophisticated in that it can use the SE or SD term. 

3. Histogram also needs to list the trait somewhere (top usually, but bottom is ok).

4. Histograms are good if you can colorize them by another trait (sex, genotype). I think Zach made progress on adding a "cofactor" to the histogram with color coding. That would be very cool. Right now we have two submenus "Sort By Name" and 'Sort By Value".  Great to add "Color By Cofactor"

## Tab 4: Probability Plot.  Ah this one is good and has a label at the top. Thanks.

1. Labels on X and Y axis are much too small, even smaller than other tabs. 

2. X and Y range of the plot is defined by the min and max of the points. This is the wrong thing to do. Range of X and Y axis should be buffered by at least 10%. If the min and max Z score is -2.2 and +2.2. then make the min and max display on the  X axis be -2.5 and +2.5.

Same applies on the Y axis. Add at least a 10% buffer. 

![screen shot 2017-03-16 at 6 45 30 pm](https://cloud.githubusercontent.com/assets/12311292/24023219/c4c84472-0a78-11e7-8c9d-37de00e79557.png)

3. P value in red font?  Just use black.  Hmm, and  p = 0.000 is probably not what we want to print in an overflow situation. Probably p < 0.001 is what we should print. But it would be good to print the -Log10(P) value instead since that can probably be computed easily up to 99.

5. Why is the "normal" line brown? Just use black.

4. Should all of our plots in GN2 have a URL printed on them at the very bottom? That might be useful.

http://gn2.genenetwork.org/show_trait?trait_id=10024412081&dataset=UCLA_BHHBF2_BRAIN_2005

# QUESTION:  What other fun univariate statistics or displays or controls could we add to make GN2 cooler, better, more useful than GN1?

**Comment by zsloan** [comment]
These were either fixed in the past or were fixed in changes I made just now to be included in next push.
