### ISSUE TITLE
Error While Using the Forgot Password Feature

### ISSUE THREAD

**Issue by moaraj** [genenetwork/genenetwork2#257]
I use GeneNetwork 1 and I think I have a username and password for gene network 2 for either mohasan@ethz.ch or mohasan@student.ethz.ch , in trying to retrieve my password since it has been so long I tried the first and got this error

   GeneNetwork penguin:gene:2.10rc3-production-adbdd62df http://gn2.genenetwork.org/n/forgot_password_submit ( 8:42AM UTC Jul 17, 2017)
    (_mysql_exceptions.OperationalError) (2006, 'MySQL server has gone away') [SQL: u'SELECT user.id AS user_id, user.email_address AS user_email_address, user.password AS user_password, user.full_name AS user_full_name, user.organization AS user_organization, user.active AS user_active, user.registration_info AS user_registration_info, user.confirmed AS user_confirmed, user.superuser AS user_superuser \nFROM user \nWHERE user.email_address = %s'] [parameters: ('mohasan@ethz.ch',)] (error)
      File "/usr/local/guix-profiles/gn2-2.10rc3/lib/python2.7/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
        raise errorvalue

**Comment by zsloan** [comment]
Yeah, we're currently aware of this issue with logging into GN2 (both the "forget password" and e-mail validation when creating a new account aren't working).

That being said, logging in currently doesn't really give much extra functionality in GN2. The only difference is that collections will just be stored temporarily (I think for either 3 days or a week) instead of permanently, but otherwise you can do all the same things. Until we get the security authentication stuff working properly we're just hiding all private/confidential data sets regardless of whether a use is logged in or not.

**Comment by pjotrp** [comment]
@fredmanglis can you see if we can create such a facility with our new tooling. We should be able to take user details from elasticsearch and mail them from GN2. I don't think we need confirmation E-mails (so, that should be disabled if it exists). A simple SMTP connection will do for sending mail out and use a standard python package. You may need to add a configuration option such as given in ./etc/default_settings.py and handled in utils.py. Name it SMTP_CONNECT and should contain a hostname and port (25 by default).

Try sending E-mail through the command line with Python before implementing in GN2.

**Comment by pjotrp** [comment]
Using 'forgotten password` on GN2 staging begets 

```
      GeneNetwork penguin:gene:2.11-rc1-master-273779dd1  http://gn2-guix.genenetwork.org/n/forgot_password_submit ( 8:19AM UTC Mar 30, 2018)
       Traceback (most recent call last):
         File "/usr/local/guix-profiles/gn2-elasticsearch/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
           rv = self.dispatch_request()
         File "/usr/local/guix-profiles/gn2-elasticsearch/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
           return self.view_functions[rule.endpoint](**req.view_args)
         File "/home/staging/gene/wqflask/wqflask/user_manager.py", line 751, in forgot_password_submit
           user_details = get_user_by_unique_column(es, "email_address", email_address)
       NameError: global name 'es' is not defined
```

**Comment by pjotrp** [comment]
@zsloan on staging we should now have working user sessions. This should work:

```python
from flask import g
def get_collection():
    if g.user_session.logged_in:
        return UserCollection()
    else:
        return AnonCollection()
```

In a template you should be able to use

```
wqflask/wqflask/templates/base.html: {% if g.user_session.logged_in %}
```

Please test and confirm.

**Comment by pjotrp** [comment]
Error is gone. See also #287
