### ISSUE TITLE
Add quantile normalization as an option

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#262]
Currently we add two datasets (one with and one without). No reason to, really, because qnorm is fast.

**Comment by abepalmer** [comment]
agree. qnorm should be performed before any winsorizing to the raw data.

**Comment by pjotrp** [comment]
It is fairly straightforward, the idea is described here:

* https://en.wikipedia.org/wiki/Quantile_normalization
  
Essentially, compute the mean over a row and plug the values back in
on the sorted columns. There is some code out there you can probably
reuse. 

* https://stackoverflow.com/questions/37935920/quantile-normalization-on-pandas-dataframe
* https://github.com/ShawnLYU/Quantile_Normalize

**Comment by pjotrp** [comment]
Does it make sense to do QNorm on the fly? It means the full 
phenotype/covariate matrix has to be in RAM.

**Comment by abepalmer** [comment]
I would think so… if the two option are qnorm in advance or on the fly, the only added calculation that I can think of is to do the qnorm, right? Genotypes and the need (imho) to precompute the GRM is unchanged. Am I missing something?
A

**Comment by pjotrp** [comment]
I think it is worth considering caching the results as they are only computed once for all phenotypes and result in a column of data. This column can be used to overwrite the (sorted) phenotypes. Covariates can also (optionally) be plugged in from that column of data.

**Comment by abepalmer** [comment]
Totally up to you, I have much less sense for what goes on behind the curtain.
A
