### ISSUE TITLE
Migrate to Python3

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#265]
By 2020 many modules will no longer support Python2 - it is already happening, for example for Rpy2 which we use heavily:

  http://www.python3statement.org/

For GN2 we should make a push for starting to use Python3. Zach, Python3 is actually better (if a bit slower). Especially for development.

I am developing the new Journal code using Python3+Flask. That will help build some experience (so far it is great).

With Guix we can split out some Python2 code because we can run the interpreters at the same time. But we should move to Python3 as much as possible. Ideally in 2018.

**Comment by pjotrp** [comment]
My proposal is to go through files one at a time and also take the opportunity to fix things like #5.

**Comment by pjotrp** [comment]
One step replace PIL with Pillow https://github.com/genenetwork/genenetwork2/pull/355

**Comment by pjotrp** [comment]
Bumped priority. Without Python3 we are in trouble upgrading software.

**Comment by chfi** [comment]
@pjotrp What's left? Should be a Trello item.
