### ISSUE TITLE
Basic Statistics figures need to update with changed values on the trait page

### ISSUE THREAD

**Issue by zsloan** [genenetwork/genenetwork2#28]
In GN1 the user has to hit the "Update Figures" button under Basic Statistics to update them based upon changed values in the "Review and Edit Data" part of the page, but since the new figures are created with javascript they should be able to update dynamically.

**Comment by pjotrp** [comment]
This working now?

**Comment by zsloan** [comment]
Doesn't seem to be. If I recall correctly, it used to work for the table
but I'm not sure if it ever worked for the figures (I'm pretty sure it was
never implemented for at least one or two of them).

I'll at least try to get the table fixed, since I'm pretty sure the code to
update it already exists. I'll also take a look at the other figures,
depending upon how difficult it looks like it'll be to update them
(hopefully not very).

**Comment by pjotrp** [comment]
@zsloan what is the status here?

**Comment by zsloan** [comment]
I apparently fixed this at some point, so closing this issue.
