### ISSUE TITLE
Reproducible correlation error

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#281]
the link is http://gn2.genenetwork.org/show_trait?trait_id=10190&dataset=HXBBXHPublish
 
when you take the trait correlation, select the first 6 and do a
correlation of those you get

```
  ERROR:wqflask.views:.corr_compute_page: 06:21:54 UTC 20180212: u'http://gn2.genenetwork.org/corr_compute'
  INFO:utility.tools:Found: file /home/zas1024/genotype_files/genotype/HXBBXH.geno

  ERROR:wqflask.views:.corr_matrix_page: 06:22:13 UTC 20180212: u'http://gn2.genenetwork.org/corr_matrix'
  ERROR:wqflask.views:.handle_bad_request: 06:22:14 UTC 20180212: can't multiply sequence by non-int of type 'float'
  ERROR:wqflask.views:.handle_bad_request: 06:22:14 UTC 20180212: u'http://gn2.genenetwork.org/corr_matrix'
  ERROR:wqflask.views:.handle_bad_request: 06:22:14 UTC 20180212: Traceback (most recent call last):
    File "/usr/local/guix-profiles/gn2-2.11rc2/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
      rv = self.dispatch_request()
    File "/usr/local/guix-profiles/gn2-2.11rc2/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
      return self.view_functions[rule.endpoint](**req.view_args)
    File "/home/production/gene/wqflask/wqflask/views.py", line 747, in corr_matrix_page
      template_vars = show_corr_matrix.CorrelationMatrix(start_vars)
    File "/home/production/gene/wqflask/wqflask/correlation_matrix/show_corr_matrix.py", line 176, in __init__
      pca = self.calculate_pca(range(len(self.traits)), corr_eigen_value, corr_eigen_vectors)
    File "/home/production/gene/wqflask/wqflask/correlation_matrix/show_corr_matrix.py", line 220, in calculate_pca
      trait_array_vectors = np.dot(corr_eigen_vectors, trait_array)
  TypeError: can't multiply sequence by non-int of type 'float'
```

@zsloan can you explain why this is going wrong?

**Comment by zsloan** [comment]
Should clarify that this is an error with the correlation matrix page, not
the correlation page.

If this error is the one I'm aware of, it's causes by one of the
PCA-related functions throwing an error. If this is the case, I can just
disable displaying that part of the page (probably the loadings table), but
I doubt I can identify the actual cause unless it's something simple like
there not being enough overlapping samples.

**Comment by pjotrp** [comment]
@zsloan has this been resolved?

**Comment by zsloan** [comment]
Not yet. I doubt I'll be able to figure out the actual cause of the error
(since I think it's something related to the matrix math), so I'll have to
just make it only show the correlation matrix in this situation. I won't be
able to push that change to production until I fix some things on my
branch, though.

**Comment by zsloan** [comment]
The change I mentioned in that comment from a year ago was pushed a long time ago, so closing this issue.
