### ISSUE TITLE
Gemma output is strange

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#282]
GEMMA with or  without LOCO works but look like a computational problem for some data sets.
With 
http://gn2.genenetwork.org/show_trait?trait_id=1427571_at&dataset=HC_M2_0606_P result of computations look off. The files mentioned in the logs look OK to me. 

@zsloan what do you think is the problem?

**Comment by zsloan** [comment]
Fixed this - the parsing function needed to be changed due to an extra column being added to output.

**Comment by pjotrp** [comment]
That works fine @zsloan. LOCO is still off. For example, http://gn2.genenetwork.org/show_trait?trait_id=1433387_at&dataset=HC_M2_0606_P run gemma with LOCO and you see we use the wrong column.
