### ISSUE TITLE
Identify modules that do not work with Python3

### ISSUE THREAD

**Issue by fredmanglis** [genenetwork/genenetwork2#289]
# Genenetwork2 Dependencies

## Dependencies with Python3 Support

   The following packages should be easy to move over to python3, simply by
   replacing python2-* with python-*.
   These packages are also present on mainline guix.

   - python2-flask
   - gunicorn
     This does not exist on mainline guix, but its dependencies do, so porting
     it over should not be much of a problem.
   - python2-elasticsearch
   - python2-sqlalchemy
   - python2-flask-sqlalchemy
   - python2-jinja2
   - python2-setuptools
   - python2-scipy
   - python2-mysqlclient
   - python2-numpy
   - python2-pandas
   - python2-passlib
   - python2-redis
   - python2-requests
   - python2-rpy2
   - python2-scipy
   - python2-simplejson
   - python2-pyyaml
   - python2-xlsxwriter
     This seems to support python3 (see https://github.com/jmcnamara/XlsxWriter)
     Also already defined in guix-bioinformatics so there's not much to do for
     this

## Dependencies Without Python3 Support

   These packages either lack Python3 support altogether, or will require some
   work to get them to work with Python3.

   - pylmm-gn2
     There's a possibility this could be ported over to Python3.
     I have run 2to3 on it, and [[https://github.com/fredmanglis/pylmm][the results are here]].
     A file test.out should also be provided with the output of running
     `scripts/test_run.sh 2>&1 | tee test.out` at the root of pylmm.
   - python2-htmlgen-gn
     This package is provided as tarball, which might makes it one of the more
     difficult packages to deal with.
     There seems to be [[https://github.com/srittau/python-htmlgen][an active fork]] of the project that might be useful,
     though the might be big API differences. This fork has Python3 support as
     far as I can tell: see https://pypi.python.org/pypi/htmlgen/0.8
   - python2-mechanize
     Does not currently have any Python3 support. It doesn't seem to be directly
     used by the code.
   - python2-numarray
     Seems to be obsolete, and part of the numpy package. Update the code to use
     the numpy version, and drop this as a dependency.
   - python2-parallel
     I have found [[https://www.parallelpython.com/downloads/pp/pp-1.6.4.4.zip][a python3 port of parallel python]] but it is in beta.
     Hopefully this will be useful.
   - python2-piddle-gn
     Also provided as a tarball.
   - python2-pil1
     Provided as a tarball. Investigate the use python-pillow instead.

## Dependencies That are Agnostic to Python

   These dependencies do not rely on python, and so will be moved over as is.

   - coreutils
   - git
   - vim
   - which
   - grep
   - r
   - r-ctl
   - r-phewas
   - r-qtl
   - r-wgcna
   - redis
   - mysql
   - gemma
   - gemma-wrapper
   - genenetwork2-files-small
   - plink-ng-gn
   - nginx
   - javascript-twitter-post-fetcher

## Dependencies I Am Not Sure About
   - qtlreaper
     This is written in C and compiled as a Python module. From what I can tell,
     it seems like it should be possible to simply use it as is, but I might be
     wrong, so I need some input, say, from Mr. Pjotr.

**Comment by pjotrp** [comment]
@fredmanglis **Inline comments**

 These packages are also present on mainline guix.

   - python2-flask
   - gunicorn
     This does not exist on mainline guix, but its dependencies do, so porting
     it over should not be much of a problem.

@fredmanglis **Should be added to main line.**

   - python2-elasticsearch
   - python2-sqlalchemy
   - python2-flask-sqlalchemy
   - python2-jinja2
   - python2-setuptools
   - python2-scipy
   - python2-mysqlclient
   - python2-numpy
   - python2-pandas
   - python2-passlib
   - python2-redis
   - python2-requests
   - python2-rpy2
   - python2-scipy
   - python2-simplejson
   - python2-pyyaml
   - python2-xlsxwriter
     This seems to support python3 (see https://github.com/jmcnamara/XlsxWriter)
     Also already defined in guix-bioinformatics so there's not much to do for
     this

## Dependencies Without Python3 Support

   These packages either lack Python3 support altogether, or will require some
   work to get them to work with Python3.

   - pylmm-gn2
     There's a possibility this could be ported over to Python3.
     I have run 2to3 on it, and [[https://github.com/fredmanglis/pylmm][the results are here]].
     A file test.out should also be provided with the output of running
     `scripts/test_run.sh 2>&1 | tee test.out` at the root of pylmm.

@fredmanglis **Can also be an external process on Python2**. It runs as an external tool already. Probably the easiest route.

   - python2-htmlgen-gn
     This package is provided as tarball, which might makes it one of the more
     difficult packages to deal with.
     There seems to be [[https://github.com/srittau/python-htmlgen][an active fork]] of the project that might be useful,
     though the might be big API differences. This fork has Python3 support as
     far as I can tell: see https://pypi.python.org/pypi/htmlgen/0.8

@fredmanglis  **htmlgen**.  It is easily replaced. A quick grep shows it is only used in three places. It is an HTML generator and maybe  there is a nicer way of doing things.

   - python2-mechanize
     Does not currently have any Python3 support. It doesn't seem to be directly
     used by the code.

@fredmanglis **drop it in favour of your new testing stuff**

   - python2-numarray
     Seems to be obsolete, and part of the numpy package. Update the code to use
     the numpy version, and drop this as a dependency.

@fredmanglis **OK**

   - python2-parallel
     I have found [[https://www.parallelpython.com/downloads/pp/pp-1.6.4.4.zip][a python3 port of parallel python]] but it is in beta.
     Hopefully this will be useful.

@fredmanglis **Drop it** we are no longer using parallel - @zsloan has dropped it. It is a bad idea to run parallel on top of parallel web services. Strip out the code if it complains.

   - python2-piddle-gn
     Also provided as a tarball.
   - python2-pil1
     Provided as a tarball. Investigate the use python-pillow instead.

@fredmanglis **This is one of our main Python3 headaches**.  Conversion is non-trivial (I checked). @fredmanglis can you find out what is the best way to do this? It is only used in three places, but... Options are: (1) drop the figures (2) upgrade to a recent drawing lib or (3) use an external Python2 process. I favour the latter. @zsloan I think most of these figures are no longer in use. Can you check?

1. [./wqflask/basicStatistics/BasicStatisticsFunctions.py](https://github.com/genenetwork/genenetwork2/tree/master/wqflask/basicStatistics/BasicStatisticsFunctions.py)
2. [./wqflask/wqflask/marker_regression/MarkerRegressionPage.py](https://github.com/genenetwork/genenetwork2/tree/master/wqflask/wqflask/marker_regression/MarkerRegressionPage.py)
3.  [./wqflask/wqflask/marker_regression/marker_regression_gn1.py](https://github.com/genenetwork/genenetwork2/tree/master/wqflask/wqflask/marker_regression/marker_regression_gn1.py)

## Dependencies That are Agnostic to Python

   These dependencies do not rely on python, and so will be moved over as is.

   - coreutils
   - git
   - vim
   - which
   - grep
   - r
   - r-ctl
   - r-phewas
   - r-qtl
   - r-wgcna
   - redis
   - mysql
   - gemma
   - gemma-wrapper
   - genenetwork2-files-small
   - plink-ng-gn
   - nginx
   - javascript-twitter-post-fetcher

## Dependencies I Am Not Sure About
   - qtlreaper
     This is written in C and compiled as a Python module. From what I can tell,
     it seems like it should be possible to simply use it as is, but I might be
     wrong, so I need some input, say, from Mr. Pjotr.

@fredmanglis **See if it works as is**. If it is a problem I'll look into it.

**Comment by zsloan** [comment]
Just for a little extra information, I believe parallel-python is only used
for correlations, and as Pjotr mentioned I have disabled it (though I need
to push that change still, since it's just my branch right now).

The parallel correlation computation *is *considerably faster than the
non-parallel (about twice as fast), but hopefully the new machine will make
this a non-issue.

**Comment by pjotrp** [comment]
@zsloan, thanks, we'll drop parallel for now. Can you also tell us which plots are still in use using PIL or Pillow?

**Comment by zsloan** [comment]
I believe only the mapping figure (using the GN1 code to generate the
image) uses them.

**Comment by pjotrp** [comment]
Thanks, I suspected as much ;). @fredmanglis , this means only https://github.com/genenetwork/genenetwork2/tree/master/wqflask/wqflask/marker_regression/marker_regression_gn1.py matters. The figure will be removed from GN2 eventually. My feeling is that we should execute it in Python2 and just load the static gif/png. No need to convert stuff and update PIL/Pillow that way.

**Comment by pjotrp** [comment]
Seeing it is 3000 lines of code I may need to do this myself :/

**Comment by fredmanglis** [comment]
@pjotrp for *qtlreaper* here's the result of trying to install it via guix with the _#:python ,python2_ argument removed:

[install_qtlreaper_guix_python3.log](https://github.com/genenetwork/genenetwork2/files/1835855/install_qtlreaper_guix_python3.log)

**Comment by pjotrp** [comment]
gcc is not in the build path. That should be easy to fix (see other python modules). But I can have a go if you want. Can I just pull from your tree?

**Comment by fredmanglis** [comment]
@pjotrp Yes you can.

**Comment by pjotrp** [comment]
It is not complete. No qtlreaper building with python3. I had to add it myself. The gcc compiler complains because there are some errors. We need to update qtlreaper to pass new errors such as

```C
Src/chromosome.c:251:3: error: ‘intargfunc’ undeclared here (not in a function)
  (intargfunc)0,     /*sq_repeat*/
   ^
Src/chromosome.c:251:14: error: expected ‘}’ before numeric constant
  (intargfunc)0,     /*sq_repeat*/
              ^
In file included from /gnu/store/ks27x0mf95gir0cdgb9h573xbava6v1k-python-3.5.3/include/python3.5m/pytime.h:6:0,
                 from /gnu/store/ks27x0mf95gir0cdgb9h573xbava6v1k-python-3.5.3/include/python3.5m/Python.h:65,
                 from Src/chromosome.c:20:
/gnu/store/ks27x0mf95gir0cdgb9h573xbava6v1k-python-3.5.3/include/python3.5m/object.h:86:5: warning: missing braces around initializer [-Wmissing-braces]
     { _PyObject_EXTRA_INIT              \
     ^
```

the last one can be a bit nasty.

**Comment by pjotrp** [comment]
I did some work on QTLreaper port to Python3 https://github.com/genenetwork/QTLReaper/compare/python3. Unfortunately it needs more work because the object types it uses changed  a lot between python2 and python3. I argue that we should run qtlreaper from python2 as long as it is useful to us. @fredmanglis we'll leave this for last.

**Comment by fredmanglis** [comment]
> > * python2-piddle-gn
> >    Also provided as a tarball.
> > * python2-pil1
> >   Provided as a tarball. Investigate the use python-pillow instead.
> 
> @fredmanglis This is one of our main Python3 headaches. Conversion is non-trivial (I checked).
> @fredmanglis can you find out what is the best way to do this? It is only used in three places, but...
> Options are: (1) drop the figures (2) upgrade to a recent drawing lib or (3) use an external Python2
> process. I favour the latter. @zsloan I think most of these figures are no longer in use. Can you
> check?

Well, from [what I can find](https://www.versioneye.com/python/piddle/0.3.dev), piddle was replaced by [Pounce](https://pypi.python.org/pypi/Pounce/1.0).
Maybe look at at that and get back to me as to its suitability to use as a replacement

**Comment by pjotrp** [comment]
Pounce is a downloader and pilled is a drawing lib - a bit different. Let's discuss today.

**Comment by pjotrp** [comment]
pylmm is being removed.
