### ISSUE TITLE
Duplicating the mechanize tests in python

### ISSUE THREAD

**Issue by fredmanglis** [genenetwork/genenetwork2#290]
The mechanize tests can be found at the following urls:

- https://github.com/genenetwork/genenetwork2/blob/master/bin/test-website
- https://github.com/genenetwork/genenetwork2/tree/master/test/lib

The entry point for the new tests is `test/requests/test-website.py` in [this fork of the repository](https://github.com/fredmanglis/genenetwork2/tree/testing)

**Comment by fredmanglis** [comment]
Running the test for R/qtl mapping causes the main system to throw the exception indicated in the following output:


RUNNING gunicorn --bind 0.0.0.0:5003 --workers=1 --timeout 180 --reload wsgi
[2018-03-19 15:32:57 +0000] [5107] [INFO] Starting gunicorn 19.7.1
[2018-03-19 15:32:57 +0000] [5107] [INFO] Listening at: http://0.0.0.0:5003 (5107)
[2018-03-19 15:32:57 +0000] [5107] [INFO] Using worker: sync
[2018-03-19 15:32:57 +0000] [5111] [INFO] Booting worker with pid: 5111
INFO:utility.tools:{}
INFO:utility.tools:[94mMr. Mojo Risin 2[0m
/home/frederick/guix_profiles/gn2/lib/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead.
  .format(x=modname), ExtDeprecationWarning
ERROR:wqflask.views:.marker_regression_page: 12:33:07 UTC 20180319: u'http://localhost:5003/marker_regression'
INFO:utility.tools:Found: file /home/frederick/genenetwork/datadir/genotype/json/BXD.json

INFO:utility.tools:Found: file /home/frederick/genenetwork/datadir/genotype/BXD.geno

/home/frederick/guix_profiles/gn2/lib/python2.7/site-packages/rpy2/robjects/functions.py:106: UserWarning: Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 93, 88

  res = super(Function, self).__call__(*new_args, **new_kwargs)
/home/frederick/guix_profiles/gn2/lib/python2.7/site-packages/rpy2/robjects/functions.py:106: UserWarning: In addition: 
  res = super(Function, self).__call__(*new_args, **new_kwargs)
/home/frederick/guix_profiles/gn2/lib/python2.7/site-packages/rpy2/robjects/functions.py:106: UserWarning: Warning messages:

  res = super(Function, self).__call__(*new_args, **new_kwargs)
/home/frederick/guix_profiles/gn2/lib/python2.7/site-packages/rpy2/robjects/functions.py:106: UserWarning: 1: 
  res = super(Function, self).__call__(*new_args, **new_kwargs)
/home/frederick/guix_profiles/gn2/lib/python2.7/site-packages/rpy2/robjects/functions.py:106: UserWarning: In fixXgeno.f2(cross, alleles) :
  res = super(Function, self).__call__(*new_args, **new_kwargs)
/home/frederick/guix_profiles/gn2/lib/python2.7/site-packages/rpy2/robjects/functions.py:106: UserWarning: 
 
  res = super(Function, self).__call__(*new_args, **new_kwargs)
/home/frederick/guix_profiles/gn2/lib/python2.7/site-packages/rpy2/robjects/functions.py:106: UserWarning:   --Omitting 95 male heterozygote genotypes on the X chromosome.

  res = super(Function, self).__call__(*new_args, **new_kwargs)
/home/frederick/guix_profiles/gn2/lib/python2.7/site-packages/rpy2/robjects/functions.py:106: UserWarning: 2: 
  res = super(Function, self).__call__(*new_args, **new_kwargs)
/home/frederick/guix_profiles/gn2/lib/python2.7/site-packages/rpy2/robjects/functions.py:106: UserWarning: In summary.cross(cross) :
  res = super(Function, self).__call__(*new_args, **new_kwargs)
/home/frederick/guix_profiles/gn2/lib/python2.7/site-packages/rpy2/robjects/functions.py:106: UserWarning:  Some markers at the same position on chr 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,X; use jittermap().

  res = super(Function, self).__call__(*new_args, **new_kwargs)
/home/frederick/guix_profiles/gn2/lib/python2.7/site-packages/rpy2/robjects/functions.py:106: UserWarning: 3: 
  res = super(Function, self).__call__(*new_args, **new_kwargs)
/home/frederick/guix_profiles/gn2/lib/python2.7/site-packages/rpy2/robjects/functions.py:106: UserWarning: In convert2riself(cross) :
  res = super(Function, self).__call__(*new_args, **new_kwargs)
/home/frederick/guix_profiles/gn2/lib/python2.7/site-packages/rpy2/robjects/functions.py:106: UserWarning:  Converting chromosome X to autosomal.

  res = super(Function, self).__call__(*new_args, **new_kwargs)
/home/frederick/guix_profiles/gn2/lib/python2.7/site-packages/rpy2/robjects/functions.py:106: UserWarning: 4: 
  res = super(Function, self).__call__(*new_args, **new_kwargs)
/home/frederick/guix_profiles/gn2/lib/python2.7/site-packages/rpy2/robjects/functions.py:106: UserWarning:  Omitting 6712 genotypes with code==2.

  res = super(Function, self).__call__(*new_args, **new_kwargs)
Starting up Gunicorn process
Set global log level to [94mWARNING[0m
runserver.py: ****** Webserver configuration ******
APPLICATION_ROOT: [92m[1mNone[0m
DEBUG: [92m[1mFalse[0m
ELASTICSEARCH_HOST: [94m[1mlocalhost[0m
ELASTICSEARCH_PORT: [94m[1m9200[0m
EXPLAIN_TEMPLATE_LOADING: [92m[1mFalse[0m
GEMMA_COMMAND: [94m[1m/home/frederick/guix_profiles/gn2/bin/gemma[0m
GEMMA_WRAPPER_COMMAND: [94m[1m/home/frederick/guix_profiles/gn2/bin/gemma-wrapper[0m
GENENETWORK_FILES: [94m[1m/home/frederick/genenetwork/datadir[0m
GITHUB_API_URL: [94m[1mhttps://api.github.com/user[0m
GITHUB_CLIENT_ID: [94m[1mec1164c698dc08a01657[0m
GITHUB_CLIENT_SECRET: [94m[1m748b07e74c36ac90e4dab94c652f845a2e123139[0m
GN_SERVER_URL: [94m[1mhttp://localhost:8880/[0m
GN_VERSION: [94m[1mpenelope:genenetwork2:2.11-rc1-testing-5ccf077f5[0m
HOME: [94m[1m/home/frederick[0m
JSONIFY_MIMETYPE: [94m[1mapplication/json[0m
JSONIFY_PRETTYPRINT_REGULAR: [94m[1mTrue[0m
JSON_AS_ASCII: [94m[1mTrue[0m
JSON_SORT_KEYS: [94m[1mTrue[0m
JS_GN_PATH: [94m[1m/home/frederick/genenetwork/javascript[0m
JS_GUIX_PATH: [94m[1m/home/frederick/guix_profiles/gn2/share/genenetwork2/javascript[0m
JS_TWITTER_POST_FETCHER_PATH: [94m[1m/home/frederick/guix_profiles/gn2/share/genenetwork2/javascript/Twitter-Post-Fetcher[0m
LOGGER_HANDLER_POLICY: [94m[1malways[0m
LOGGER_NAME: [94m[1mwqflask[0m
LOG_BENCH: [94m[1mTrue[0m
LOG_LEVEL: [94m[1mWARNING[0m
LOG_LEVEL_DEBUG: [94m[1m0[0m
LOG_SQL: [94m[1mFalse[0m
LOG_SQL_ALCHEMY: [94m[1mFalse[0m
MAX_CONTENT_LENGTH: [92m[1mNone[0m
ORCID_CLIENT_ID: [94m[1mAPP-FCLYC3Q7PEXO3BFJ[0m
ORCID_CLIENT_SECRET: [94m[1m466eb7f6-0575-49f2-9d84-20423198b7e6[0m
ORCID_TOKEN_URL: [94m[1mhttps://sandbox.orcid.org/oauth/token[0m
PERMANENT_SESSION_LIFETIME: [94m[1m31 days, 0:00:00[0m
PLINK_COMMAND: [94m[1m/home/frederick/guix_profiles/gn2/bin/plink2[0m
PREFERRED_URL_SCHEME: [94m[1mhttp[0m
PRESERVE_CONTEXT_ON_EXCEPTION: [92m[1mNone[0m
PROPAGATE_EXCEPTIONS: [92m[1mNone[0m
PYLMM_COMMAND: [94m[1m/home/frederick/guix_profiles/gn2/bin/pylmm_redis[0m
SECRET_HMAC_CODE: [94m[1mN\H@\`d^a;OM6a:*c[0m
SECRET_KEY: [92m[1mNone[0m
SECURITY_CONFIRMABLE: [94m[1mTrue[0m
SECURITY_EMAIL_SENDER: [94m[1mno-reply@genenetwork.org[0m
SECURITY_POST_LOGIN_VIEW: [94m[1m/thank_you[0m
SECURITY_RECOVERABLE: [94m[1mTrue[0m
SECURITY_REGISTERABLE: [94m[1mTrue[0m
SECURITY_TRACKABLE: [94m[1mTrue[0m
SEND_FILE_MAX_AGE_DEFAULT: [94m[1m12:00:00[0m
SERVER_NAME: [92m[1mNone[0m
SERVER_PORT: [94m[1m5003[0m
SESSION_COOKIE_DOMAIN: [92m[1mNone[0m
SESSION_COOKIE_HTTPONLY: [94m[1mTrue[0m
SESSION_COOKIE_NAME: [94m[1msession[0m
SESSION_COOKIE_PATH: [92m[1mNone[0m
SESSION_COOKIE_SECURE: [92m[1mFalse[0m
SESSION_REFRESH_EACH_REQUEST: [94m[1mTrue[0m
SMTP_CONNECT: [94m[1msmtp.gmail.com:587[0m
SMTP_PASSWORD: [94m[1mqkcubljkengvbmcn[0m
SMTP_USERNAME: [94m[1mfredmanglis@gmail.com[0m
SQL_ALCHEMY_POOL_RECYCLE: [94m[1m3600[0m
SQL_URI: [94m[1mmysql://gn2:genenetwork2@127.0.0.1/db_webqtl_s[0m
TEMPLATES_AUTO_RELOAD: [92m[1mNone[0m
TESTING: [92m[1mFalse[0m
TMPDIR: [94m[1m/tmp[0m
TRAP_BAD_REQUEST_ERRORS: [94m[1mTrue[0m
TRAP_HTTP_EXCEPTIONS: [92m[1mFalse[0m
USE_GN_SERVER: [94m[1mFalse[0m
USE_REDIS: [94m[1mTrue[0m
USE_X_SENDFILE: [92m[1mFalse[0m
WEBSERVER_BRANDING: [92m[1mNone[0m
WEBSERVER_DEPLOY: [92m[1mNone[0m
WEBSERVER_MODE: [94m[1mDEBUG[0m
WEBSERVER_URL: [94m[1mhttp://localhost:5003/[0m
('PIL_LOCATION:', '/home/frederick/guix_profiles/gn2/lib/python2.7/site-packages/PIL1/Image.pyc')
[1] "qtl"       "tools"     "stats"     "graphics"  "grDevices" "utils"    
[7] "datasets"  "methods"   "base"     

Genodata: 6   3806 97 B H D 
 --Read the following data:
	 93  individuals
	 3806  markers
	 2  phenotypes
 --Cross type: f2 
ERROR:wqflask.views:.handle_bad_request: 12:33:14 UTC 20180319: Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 93, 88

ERROR:wqflask.views:.handle_bad_request: 12:33:14 UTC 20180319: u'http://localhost:5003/marker_regression'
ERROR:wqflask.views:.handle_bad_request: 12:33:14 UTC 20180319: Traceback (most recent call last):
  File "/home/frederick/guix_profiles/gn2/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/frederick/guix_profiles/gn2/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/frederick/genenetwork/genenetwork2/wqflask/wqflask/views.py", line 623, in marker_regression_page
    template_vars = marker_regression.MarkerRegression(start_vars, temp_uuid)
  File "/home/frederick/genenetwork/genenetwork2/wqflask/wqflask/marker_regression/marker_regression.py", line 199, in __init__
    results = rqtl_mapping.run_rqtl_geno(self.vals, self.dataset, self.method, self.model, self.permCheck, self.num_perm, self.do_control, self.control_marker, self.manhattan_plot, self.pair_scan)
  File "/home/frederick/genenetwork/genenetwork2/wqflask/wqflask/marker_regression/rqtl_mapping.py", line 43, in run_rqtl_geno
    cross_object = add_phenotype(cross_object, sanitize_rqtl_phenotype(vals))                 # Add the phenotype
  File "/home/frederick/genenetwork/genenetwork2/wqflask/wqflask/marker_regression/rqtl_mapping.py", line 114, in add_phenotype
    ro.r('the_cross$pheno <- cbind(pull.pheno(the_cross), the_pheno = '+ pheno_as_string +')')
  File "/home/frederick/guix_profiles/gn2/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 319, in __call__
    res = self.eval(p)
  File "/home/frederick/guix_profiles/gn2/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/home/frederick/guix_profiles/gn2/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 93, 88


I still don't understand what the mapping does, so I'll skip this for now, and come back to it after implementing the other tests.

**Comment by pjotrp** [comment]
@fredmanglis if you tell me how to duplicate the error I can take a look.

**Comment by fredmanglis** [comment]
@pjotrp 

Get my latest changes, then run something like:

    env GN2_PROFILE=~/guix_profiles/gn2 ./bin/genenetwork2 \
    ../custom_settings.py -c \
    ../test/requests/test-website.py http://localhost:5003 -m

You'll note that the tests fail at the `R/qtl mapping tool selection` stage.

Now if you look at the output of the flask application (serving at url given), you should see a similar error to the one in the given file.

**Comment by fredmanglis** [comment]
@pjotrp I was able to reproduce the error, on the browser:

### Steps
* Go to http://localhost:5003 (or whichever url you'll be using)
* Leave "Get Any" blank
* Enter MEAN=(15 16) LRS=(23 46) in "Combined" field
* Click "Search"
* Click on first link (1443823_s_at) and wait for page to complete loading
* Expand "Mapping Tools" accordion
* Click on the "R/qt" link
* Click the "Compute" button
* A new tab pops up, and after a while, the exception is shown.

**Comment by zsloan** [comment]
Hm, this seems to work okay on production and my branch.

**Comment by pjotrp** [comment]
Yeah, it is probably a data problem. We are running on the small database and old genotype files (which should match). I'll look at it soon.
