### ISSUE TITLE
Migrate across to Python3

### ISSUE THREAD

**Issue by fredmanglis** [genenetwork/genenetwork2#292]
This is an "umbrella" issue that covers issues #289, #290 and #291 

It also holds the miscellaneous notes that do not fit in the other three issues.

**Comment by robwwilliams** [comment]
Thanks much Fred for all this good work. Pjotr and I trying to get Upwork to work for all of us.

**Comment by fredmanglis** [comment]
@zsloan @pjotrp Is there any reason https://github.com/genenetwork/genenetwork2/blob/testing/wqflask/base/trait_collection.py has 2 different `def __init__(self, ...` statements (lines 3-4 and 35-39)?

Which is the correct __init__?

**Comment by zsloan** [comment]
Huh, I'm pretty sure this file isn't used and needs to be removed. The file
that does the same stuff is /wqflask/wqflask/collect.py (and sorta also
user_manager.py in the same directory, which has the collection functions
for user and anonymous collections respectively).

**Comment by pjotrp** [comment]
@zsloan: please remove dead code. You can store it in a folder named 'obsolete' to make sure it is no longer in use. We really delete it after a week or so.

**Comment by pjotrp** [comment]
Pillow progress on #355!

**Comment by pjotrp** [comment]
Of the outstanding python3 packages (correct me if I am wrong @fredmanglis):

* pylmm-gn2 - dropped
* python2-htmlgen-gn - still have to migrate to new fork
   There seems to be [[https://github.com/srittau/python-htmlgen][an active fork]] of the project that might be useful, though the might be big API differences. This fork has Python3 support as
    far as I can tell: see https://pypi.python.org/pypi/htmlgen/0.8
* python2-mechanize - only used for testing (no need to port)
* python2-numarray - should be easy
    Seems to be obsolete, and part of the numpy package. Update the code to use
    the numpy version, and drop this as a dependency.
 * python2-parallel - dropped
 * python2-piddle-gn & python2-pil1 - in progress #355 
 * qtlreaper - run outside webserver

By the look of this only qtlreaper is the main blocker.
