### ISSUE TITLE
Some valid requests show as errors in the logs

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#296]
```
ERROR:wqflask.views:.docedit: 09:53:41 UTC 20180321: u'http://gn2.genenetwork.org/docedit?entry=links'
ERROR:wqflask.views:.index_page: 09:53:51 UTC 20180321: u'http://gn2.genenetwork.org/'
ERROR:wqflask.views:.submit_trait_form: 09:54:08 UTC 20180321: u'http://gn2.genenetwork.org/submit_trait'
```

**Comment by pjotrp** [comment]
@zsloan: to see info messages run GN2 with something like 

```bash
env SERVER_PORT=5003 WEBSERVER_MODE=DEBUG LOG_LEVEL=INFO GN2_PROFILE=/home/wrk/opt/gn-latest ./bin/genenetwork2 etc/default_settings.py -gunicorn-dev
```

You'll see

```
INFO:wqflask.views:.index_page: Sending index_page
INFO:wqflask.views:.index_page: u'http://localhost:5003/'
```

**Comment by zsloan** [comment]
Does it need to be passed in the command line? Because that might explain
why I couldn't get the info/debug logs to show up when I changed the log
level in the settings file.

**Comment by pjotrp** [comment]
WEBSERVER_MODE=DEBUG LOG_LEVEL=INFO and also be set in settings - see default_settings.py. I prefer the command line.

If it does not work, it is a bug.

**Comment by zsloan** [comment]
Ahhh, I see what I was doing wrong; I made the change in zach_settings.py
despite the command in run_staging.sh not even importing it. I'll go
through and remove the logs which are wrongly logged as errors now.

**Comment by pjotrp** [comment]
Handled searches containing invalid data in the URL with https://github.com/pjotrp/genenetwork2/commit/babe7424bfc06b2436b6e824389cf795afdf0a73
