### ISSUE TITLE
Add pylmm gwas (Hs) 

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#30]

**Comment by pjotrp** [comment]
I think we have integrated approaches now. Zach, pylmm and gemma are missing for

http://gn2.genenetwork.org/show_trait?trait_id=10023823808&dataset=HBTRC-MLC_0611

**Comment by zsloan** [comment]
We don't have a genotypes file for that, so can't do mapping. If we can get
the genotypes in BIMBAM or the PLINK formats I could add it.
