### ISSUE TITLE
Get genotypes directly from genofile

### ISSUE THREAD

**Issue by zsloan** [genenetwork/genenetwork2#325]
Currently you can only view genotypes on the trait page if the genotypes are stored in the MySQL database. Instead, it should be possible to just get them directly from the genofile.

The main (and possibly only) concern about this would be related to running searches (since they wouldn't be in MySQL), but it should at least be possible to view markers on the trait page with their values loaded from the genofile. Adding them to a collection (from which they can be used as cofactors) should be possible from the trait page.

**Comment by chfi** [comment]
Maybe we should put this in the Trello board, if it's important @zsloan @pjotrp
