### ISSUE TITLE
Support GN1 freeze files

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#327]
The Freeze files were implemented in about 2008-2009 by David Crowell
   to avoid complex table joins and speed up correlation computation. I
   thought that Lei actually got this working in GN2 at some point. We
   absolutely need this too work because we need correlations to compute
   wickedly fast and there is no way to do that from a standard MySQL
   table structure. There is from these "materialized views" of the data.
   
   [3]https://en.wikipedia.org/wiki/Materialized_view
   
See E-mail Wed, 22 Aug 2018

**Comment by chfi** [comment]
@pjotrp status on this?
