### ISSUE TITLE
Database connector timeout

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#33]
Need to replicate the issue for testing/fixing

**Comment by pjotrp** [comment]
The settings for 

    https://pythonhosted.org/Flask-SQLAlchemy/config.html

suggest to increase SQLALCHEMY_POOL_TIMEOUT and decrease SQLALCHEMY_POOL_RECYCLE. We may want to increase the size of the pool a bit.

We may also want do expand the timeout for MySQL

    http://www.rackspace.com/knowledge_center/article/how-to-change-the-mysql-timeout-on-a-server 

Currently it is using the default of 8 hours.

**Comment by zsloan** [comment]
Seems to be fixed (hopefully). If anyone has this occur let us know. It'll usually occur as an error that is resolved when you refresh the page.
