### ISSUE TITLE
Define sample/strain groups somewhere

### ISSUE THREAD

**Issue by zsloan** [genenetwork/genenetwork2#335]
Currently samples/strains for a group are only split into groups based upon whether they appear in the group's genofile, with the ones that appear in the DB but not the genofile being put into an "Other" category. 

Ideally the group(s) a sample/strain belongs to would be indicated somewhere in the DB, so that more than just those 2 groups could exist (for example for groups like MDP, where there might be multiple relevant sub-groups).

**Comment by zsloan** [comment]
Marking this as "hard difficulty" because it's the sort of thing that's going to require a significant redesign to the way we store data.

**Comment by chfi** [comment]
@zsloan should probably go on Trello

**Comment by zsloan** [comment]
This is more "a thing to consider when doing a full DB redesign" rather than its own bug/problem, and there's not really any risk of it being forgotten (since we re-encounter the consequences of this frequently). So it might be okay to just leave this out entirely, since it's not a clearly defined task.
