### ISSUE TITLE
Couple eigentrait additions/changes

### ISSUE THREAD

**Issue by zsloan** [genenetwork/genenetwork2#336]
- Assert that the mean of an eigentrait, which is normalized to z-scores, is 0

- Add option to flip polarity of an eigentrait

**Comment by zsloan** [comment]
This is related to implementing the PCA traits feature from GN1, which is now partially done. Currently (on my branch) when you do correlation matrix it will calculate the PCA traits and you can view them and add them to a collection from the trait page (not from the correlation matrix page).

There are some issues that need to be addressed regarding how Temp traits are dealt with by various features. While you can add PCA traits (or any other temp/submitted trait) to a collection, you can't actually do anything with them. Only the trait page is "equipped" with the code that correctly grabs the trait information for those traits. 

Code dealing with temp traits should probably be separated out of the show trait page so that any feature can use temp traits. I obviously don't want to have to add code to every single feature saying "by the way, if it's a temp trait do X, Y, and Z instead."

**Comment by chfi** [comment]
@zsloan status on this? If it's still important let's make a Trello item, but if not, let's leave it until it comes up in the future.

**Comment by zsloan** [comment]
This is basically done (there might be some feature that still has issues with temp traits, but it's the sort of thing that would be easy to fix if it popped up and works for the major features like mapping/correlations). There's probably a better way to do this, but it functions fine.
