### ISSUE TITLE
GN2 writes images to wrong directory

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#338]
git shows these files in the source tree on production:

        wqflask/wqflask/static/output/Itvl_udjcpqpE.jpeg
        wqflask/wqflask/static/output/Itvl_uqDUAIut.jpeg
        wqflask/wqflask/static/output/Itvl_uzXeSCx9.jpeg
        wqflask/wqflask/static/output/Itvl_wPPjtGmf.jpeg
        wqflask/wqflask/static/output/Itvl_ypSTJJ0I.jpeg
        wqflask/wqflask/static/output/Itvl_zAUYx2Ii.jpeg
        wqflask/wqflask/static/output/Itvl_ztiGTJPp.jpeg
        wqflask/wqflask/static/output/Reg_2hPuIp9L.gif
        wqflask/wqflask/static/output/Reg_4dHUyCUv.gif
        wqflask/wqflask/static/output/Reg_6l0pb3Qt.gif
        wqflask/wqflask/static/output/Reg_91G93CHe.gif
        wqflask/wqflask/static/output/Reg_95s2Nym7.gif
        wqflask/wqflask/static/output/Reg_9Kyohpyv.gif

@zsloan can you change this to use TMPDIR?

**Comment by zsloan** [comment]
I can't find anything still writing out to this directory. It appears that qtlreaper results (both the figure and the permutation chart when applicable) used to be sent to that directory, but at some point the path was changed to the correct TMPDIR.

Closing, but I'll keep an eye out in that directory periodically.
