### ISSUE TITLE
Update htmlgen 2.2.2 code

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#360]
Currently GN2 uses htmlgen for some older code (htmlgen is from 1997!). Original docs:
http://soc.if.usp.br/manual/python-htmlgen/html/main.html

A new version exists, but as @fredmanglis points out, it has changed.

@zsloan, we'll ask Fred to make the conversion, but can you check whether code can be stripped that is no longer in use? Please confirm here when you are happy.

**Comment by pjotrp** [comment]
@zsloan any progress on this? @fredmanglis is starting on the conversion...

**Comment by zsloan** [comment]
It is only in display_mapping_results.py. There were imports in a few other places which I removed (though currently only on my branch.

**Comment by pjotrp** [comment]
@fredmanglis can you take a look?

**Comment by zsloan** [comment]
Minor thing, but the removed imports in other files aren't just on my branch now; I pushed them with another fix earlier this week (I think the one Rob was talking about with changing the index page).

**Comment by pjotrp** [comment]
ping @fredmanglis

**Comment by fredmanglis** [comment]
@pjotrp pong

**Comment by fredmanglis** [comment]
@pjotrp Seems I missed the notification on this. I will look at it this week, and get back to you.

**Comment by fredmanglis** [comment]
@pjotrp @zsloan I got some work done on migrating to the new HTMLGen in branch [360_update_htmlgen](https://github.com/fredmanglis/genenetwork2/tree/360_update_htmlgen) of my fork.

I have created [pull request #366](https://github.com/genenetwork/genenetwork2/pull/366) which you can review.

To test this, you will need the updated definitions in [guix-bioinformatics]() added in commits [888dcd025b042cfe2708bd52d2914687cf4244ab](https://gitlab.com/genenetwork/guix-bioinformatics/commit/888dcd025b042cfe2708bd52d2914687cf4244ab) and [d8a06ad808bf5312bf55d9ef0b4dcbb5dc792a17](https://gitlab.com/genenetwork/guix-bioinformatics/commit/d8a06ad808bf5312bf55d9ef0b4dcbb5dc792a17).

Please have a look and get back to me.
