### ISSUE TITLE
Need to hide mapping option when no/bad genotypes

### ISSUE THREAD

**Issue by zsloan** [genenetwork/genenetwork2#361]
Currently there are some data sets which have bad/dummy genotype files. This is usually because the dummy .geno file was converted into a BIMBAM file. GN2 gives the user an informative error telling them the genotype file has problems, but it would probably be ideal to simply hide mapping for traits without proper genotypes.

An example group with this issue is GTEx_v5 - http://gn2-zach.genenetwork.org/show_trait?trait_id=ENSG00000093010.7&dataset=GTEXv5_BrFr_0915

**Comment by pjotrp** [comment]
Have we documented how to convert these files somewhere? Also, should we drop the older type files?

**Comment by zsloan** [comment]
We need both the .geno and BIMBAM files because the .geno are both used by
qtlreaper and used to generate the sample list for the group/inbred set
(this obviously isn't ideal, but it's just one of the things that we'll
need to change before switching to a single genotype file format).

I don't think it's documented anywhere, so I should probably add it to the
readme. The file itself is self-explanatory (there is a file in
/wqflask/maintenance called convert_geno_to_bimbam.py that runs through the
entire genotype_files/genotype directory and converts its contents into
genotype_files/genotype/bimbam ).

**Comment by pjotrp** [comment]
We are going to modify qtlreaper anyway. So that would take away the .geno needs, right?

**Comment by zsloan** [comment]
Still need it for getting the sample list*, and I actually forgot one thing
in my last comment - it's also used when drawing the mapping results. This
Dataset objects (a qtlreaper object) is created and is then used to iterate
through chromosomes or something. But as long as QTL reaper is changed to
take a different format, these things aren't a problem (and the code that
gets the samplelist from the .geno file could just be changed to get it
frmo whatever other format we use).

* For some groups, like BXD, samples are split into (for BXD) "BXD" and
"Other" subsets. This is presumably because there are times that we want to
include samples that aren't technically from BXD; it's logic that carried
over from GN1. The way the logic works is that it gets the "primary"
samplelist/strainlist from the .geno file, and then compares it with the
samples/strains it finds under that group in the MySQL database, and
anything in the latter but not the former is placed in the "Other" table.

**Comment by pjotrp** [comment]
Cool. We should probably settle for R/qtl2 formats and have GEMMA use those too. See https://github.com/genetics-statistics/GEMMA/issues/131

**Comment by zsloan** [comment]
We technically already have a database column (MappingMethodId in InbredSet) that the code uses to decide which mapping methods to show, but it's not always up to date so things slip through the cracks. I'm not sure if it makes more sense to actually directly check the genotype files when running mapping than it does to just keep the content of that table up to date.

All of this should ultimately be resolved when we switch to the R/qtl2 format for everything. I'll hold off on closing this for now
