### ISSUE TITLE
GeneNetwork error: reaper: Memory error for MAX_MARKERNAME_SIZE

### ISSUE THREAD

**Issue by smahaffey** [genenetwork/genenetwork2#362]
I don't think this issue is the same as any open issues.  

I just tested the Tabakoff 2009 HXB alcohol consumption dataset (http://gn2.genenetwork.org/show_trait?trait_id=10190&dataset=HXBBXHPublish) for mapping with GEMMA with the defaults.  Interval Mapping works and R/QTL works.

Full Stack trace:
GeneNetwork tux01:gene:2.11-rc2-production-9fbd347f5  http://gn2.genenetwork.org/run_mapping ( 5:50PM UTC Mar 25, 2019)
       Traceback (most recent call last):
         File "/usr/local/guix-profiles/gn-latest-20181119/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
           rv = self.dispatch_request()
         File "/usr/local/guix-profiles/gn-latest-20181119/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
           return self.view_functions[rule.endpoint](**req.view_args)
         File "/export/local/home/gn2/production/gene/wqflask/wqflask/views.py", line 710, in mapping_results_page
           gn1_template_vars = display_mapping_results.DisplayMappingResults(result).__dict__
         File "/export/local/home/gn2/production/gene/wqflask/wqflask/marker_regression/display_mapping_results.py", line 231, in __init__
           self.genotype = self.dataset.group.read_genotype_file()
         File "/export/local/home/gn2/production/gene/wqflask/base/data_set.py", line 399, in read_genotype_file
           genotype_1.read(full_filename)
       SystemError: reaper: Memory error for MAX_MARKERNAME_SIZE

**Comment by zsloan** [comment]
This is an issue we're aware of. It's apparently an issue with qtlreaper*, which Pjotr is going to rewrite later. It doesn't happen consistently, so if you get this error you should still be able to view the results if you run the same thing again (might take a couple tries, though).

* qtlreaper is still used when drawing the mapping figure, even if you do mapping with GEMMA or some other method. This is because the mapping figure code is borrowed from GN1 and iterates through this object creates by qtlreaper.

**Comment by smahaffey** [comment]
Sorry for reporting it again.  I did search issues on GitHub and nothing looked quite like this.  Just wanted to let you know.  It did work on the second try.

**Comment by zsloan** [comment]
Oh, that's no problem. By all means never hesitate to let us know any time
you encounter an error, since a lot of stuff slips through the cracks.

**Comment by pjotrp** [comment]
qtlreaper is written in C and overwrites memory sometimes. Would be a nice 1-2 week hacking job to fix qtlreaper.

**Comment by pjotrp** [comment]
@chfi is rewriting qtlreaper!

**Comment by pjotrp** [comment]
Fixed.
