### ISSUE TITLE
Multi-trait heat map failed

### ISSUE THREAD

**Issue by echesler** [genenetwork/genenetwork2#368]
Selected multiple traits from phenotype correlations to Ap3m2 in the hippocampus. 
Selected "Heat Map"

    GeneNetwork tux01:gene:2.11-rc2-production-2abbf82b4 http://gn2.genenetwork.org/heatmap (11:25AM UTC Sep 17, 2019)
    reaper: the length of the strain list and the value list are different, 
or they are less than 8  (error)
        trait = trimmed_values)
    IndexError: reaper: the length of the strain list and the value list are different,

**Comment by echesler** [comment]
One of my traits had missing data, deselecting this trait fixed the problem. Record 20761.

**Comment by pjotrp** [comment]
@zsloan can you take a look and see if we can avoid the error message? Maybe the new reaper resolves it.

**Comment by zsloan** [comment]
Yeah; this is also a good excuse to go ahead and move heatmap to using the
new reaper regardless of whether that's the cause of the error.

**Comment by zsloan** [comment]
Hm, selecting some results from the correlation of this trait against BXD
phenotypes and using heatmap didn't cause the error:
http://gn2-zach.genenetwork.org/show_trait?trait_id=1432125_at&dataset=HC_M2_0606_P

Might need to know the specific trait(s).

**Comment by fredmanglis** [comment]
Migrated to the [gemtext issue tracker](https://github.com/genenetwork/gn-gemtext-threads/blob/main/issues/multi-trait-heatmap-failed.gmi)
