### ISSUE TITLE
GEMMA_error

### ISSUE THREAD

**Issue by dlinsen1** [genenetwork/genenetwork2#370]
GeneNetwork tux01:gene:2.11-rc2-production-2abbf82b4 http://gn2.genenetwork.org/run_mapping ( 8:24PM UTC Sep 23, 2019)
    invalid literal for int() with base 10: 'X' (error)
      File "/export/local/home/gn2/production/gene/wqflask/base/data_set.py", line 196, in __init__
        marker['chr'] = int(marker['chr'])

**Comment by pjotrp** [comment]
Aged.
