### ISSUE TITLE
Login_error

### ISSUE THREAD

**Issue by dlinsen1** [genenetwork/genenetwork2#371]
GeneNetwork tux01:gene:2.11-rc2-production-2abbf82b4 http://gn2.genenetwork.org/n/login ( 7:40PM UTC Sep 23, 2019)
    Invalid input of type: 'NoneType'. Convert to a byte, string or number first. (error)
      File "/usr/local/guix-profiles/gn-latest-20190905/lib/python2.7/site-packages/redis/connection.py", line 117, in encode
        "byte, string or number first." % typename)

**Comment by pjotrp** [comment]
@zsloan this is a known bug!

**Comment by zsloan** [comment]
I forgot to push the change to production. It is on production now.
