### ISSUE TITLE
GeneNetwork error: 404 Not Found: The requested URL was not found on the server.

### ISSUE THREAD

**Issue by karakulahg** [genenetwork/genenetwork2#372]
Hello: When I try to reach the glossary page (http://genenetwork.org/glossary.html), I encounter the following error:  

(GeneNetwork error: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and tr)

    GeneNetwork tux01:gene:2.11-rc2-production-945abccdb http://genenetwork.org/glossary.html ( 9:32AM UTC Jan 29, 2020)
    404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again. (error)
      File "/usr/local/guix-profiles/gn-latest-20190905/lib/python2.7/site-packages/flask/app.py", line 1793, in raise_routing_exception
        raise request.routing_exception

**Comment by robwwilliams** [comment]
Dear Karakulahg,
Thanks. We will get this fixed in next 12 hours. In the meantime, please
check the glossary in one of the “Time Machine”  versions of GeneNetwork
(links on main page: right side)

---------- Forwarded message ---------

**Comment by pjotrp** [comment]
@robwwilliams @BonfaceKilz will create a new stub on github to create the new page for GN2.
