### ISSUE TITLE
(Bug) Unicode error encoding error on search page

### ISSUE THREAD

**Issue by BonfaceKilz** [genenetwork/genenetwork2#392]
**Description**

The following error log is displayed when you make a query that looks like: __search?species=mouse&group=BXD&type=Phenotypes&dataset=BXDPublish&search_terms_or=cb&search_terms_and=&FormID=searchResult__

<details>
<summary><i>Click here to see debug info:</i></summary>
<pre>
GeneNetwork susa:genenetwork2:2.11-rc2-use-guix-datatables-extensions-dependency-464ee0ad2 http://localhost:5004/search?species=mouse&group=BXD&type=Phenotypes&dataset=BXDPublish&search_terms_or=*&search_terms_and=&FormID=searchResult (11:43AM UTC May 12, 2020)
      'latin-1' codec can't encode characters in position 58-59: ordinal not in range(256) (error)
        File "/home/bonface/projects/genenetwork2/wqflask/base/trait.py", line 433, in retrieve_trait_info
          holder = holder.encode('latin1')
</pre>
</details>

<details>
<summary><i>Click to toggle full stack trace:</i></summary>
<pre>
      GeneNetwork susa:genenetwork2:2.11-rc2-use-guix-datatables-extensions-dependency-464ee0ad2  http://localhost:5004/search?species=mouse&group=BXD&type=Phenotypes&dataset=BXDPublish&search_terms_or=cb&search_terms_and=&FormID=searchResult ( 9:57AM UTC May 13, 2020)
       Traceback (most recent call last):
         File "/home/bonface/.guix-profile/lib/python2.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
           rv = self.dispatch_request()
         File "/home/bonface/.guix-profile/lib/python2.7/site-packages/flask/app.py", line 1936, in dispatch_request
           return self.view_functions[rule.endpoint](**req.view_args)
         File "/home/bonface/projects/genenetwork2/wqflask/wqflask/views.py", line 184, in search_page
           the_search = search_results.SearchResultPage(request.args)
         File "/home/bonface/projects/genenetwork2/wqflask/wqflask/search_results.py", line 91, in __init__
           self.gen_search_result()
         File "/home/bonface/projects/genenetwork2/wqflask/wqflask/search_results.py", line 117, in gen_search_result
           this_trait = trait.GeneralTrait(dataset=self.dataset, name=trait_id, get_qtl_info=True, get_sample_info=False)
         File "/home/bonface/projects/genenetwork2/wqflask/base/trait.py", line 80, in __init__
           self = retrieve_trait_info(self, self.dataset, get_qtl_info=get_qtl_info)
         File "/home/bonface/projects/genenetwork2/wqflask/base/trait.py", line 433, in retrieve_trait_info
           holder = holder.encode('latin1')
       UnicodeEncodeError: 'latin-1' codec can't encode characters in position 148-149: ordinal not in range(256)
     </pre>
</details>

The data is obtained from an aws bucket here [here](https://s3.amazonaws.com/genenetwork2/db_webqtl_s.zip)

**To Reproduce**

- Import the [data](https://s3.amazonaws.com/genenetwork2/db_webqtl_s.zip) from AWS
- Run the gn2 from your workstation
- Use the query params: __search?species=mouse&group=BXD&type=Phenotypes&dataset=BXDPublish&search_terms_or=cb&search_terms_and=&FormID=searchResult__

**Expected behavior**
The tables with the extra char-sets from utf-8 should be displayed properly

**Screenshots**

![image](https://user-images.githubusercontent.com/11820306/81799145-98e3ac00-9519-11ea-959b-6cae6a9f3802.png)

**Environment setup (please complete the following information):**
 - OS: arch linux
 - GN Version: latest on master branch

**Additional context**

This behaviour is not in production.

**Comment by zsloan** [comment]
Ah, I replied to the other email before seeing this! I think this might be
because the GN2 webserver (on production and my branch) is being started
with the following SQL_URI - SQL_URI=mysql://webqtlout:webqtlout@tux01
/db_webqtl?charset=latin1

The "charset=latin1" was added a while back because there was an issue
where the text in the DB was encoded latin1 and using utf-8 encoding caused
some search results to display characters incorrectly. I think adding that
to the URI would probably fix the error you're getting.

**Comment by BonfaceKilz** [comment]
Thanks! Let me try that out :smile:

**Comment by BonfaceKilz** [comment]
Also noticed the same issue yesterday on gn2 prod with the following search params: **search?species=mouse&group=BXD&type=Hippocampus+mRNA&dataset=HC_M2_0606_P&search_terms_or=*&search_terms_and=&FormID=searchResult**. Here's the full stack trace:

<details>
<summary>Click to toggle full stack trace</summary>
<pre>
  GeneNetwork tux01:gene:2.11-rc2-HEAD-153f48e64  http://gn2.genenetwork.org/search?species=mouse&group=BXD&type=Hippocampus+mRNA&dataset=HC_M2_0606_P&search_terms_or=*&search_terms_and=&FormID=searchResult (10:59PM UTC Jun 04, 2020)
       Traceback (most recent call last):
         File "/usr/local/guix-profiles/gn-latest-20200513/lib/python2.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
           rv = self.dispatch_request()
         File "/usr/local/guix-profiles/gn-latest-20200513/lib/python2.7/site-packages/flask/app.py", line 1936, in dispatch_request
           return self.view_functions[rule.endpoint](**req.view_args)
         File "/export/local/home/gn2/production/gene/wqflask/wqflask/views.py", line 184, in search_page
           the_search = search_results.SearchResultPage(request.args)
         File "/export/local/home/gn2/production/gene/wqflask/wqflask/search_results.py", line 91, in __init__
           self.gen_search_result()
         File "/export/local/home/gn2/production/gene/wqflask/wqflask/search_results.py", line 117, in gen_search_result
           this_trait = trait.GeneralTrait(dataset=self.dataset, name=trait_id, get_qtl_info=True, get_sample_info=False)
         File "/export/local/home/gn2/production/gene/wqflask/base/trait.py", line 80, in __init__
           self = retrieve_trait_info(self, self.dataset, get_qtl_info=get_qtl_info)
         File "/export/local/home/gn2/production/gene/wqflask/base/trait.py", line 479, in retrieve_trait_info
           description_string = unicode(str(trait.description).strip(codecs.BOM_UTF8), 'utf-8')
       UnicodeDecodeError: 'utf8' codec can't decode byte 0xa0 in position 36: invalid start byte

</pre>
</details>

**Comment by BonfaceKilz** [comment]
https://github.com/genenetwork/genenetwork2/commit/cef130716782cf5c06453705bee7ab6aed1dcce0#commitcomment-40266838

**Comment by BonfaceKilz** [comment]
After the mysql update, on penguin2, https://github.com/genenetwork/genenetwork2/pull/405 works. Here's the difference in the character sets:

<details>
<summary><b>Character sets on penguin2</b></summary>
<pre>
MariaDB [db_webqtl_s]> show variables like "character_set%";
+--------------------------+----------------------------+
| Variable_name            | Value                      |
| character_set_client     | utf8mb4                    |
| character_set_connection | utf8mb4                    |
| character_set_database   | latin1                     |
| character_set_filesystem | binary                     |
| character_set_results    | utf8mb4                    |
| character_set_server     | utf8mb4                    |
| character_set_system     | utf8                       |
| character_sets_dir       | /usr/share/mysql/charsets/ |
+--------------------------+----------------------------+
8 rows in set (0.00 sec)
</pre>
</details>

<details>
<summary><b>Character sets on tux01</b></summary>
<pre>
+--------------------------+-------------------+
| VARIABLE_NAME            | SESSION_VALUE     |
+--------------------------+-------------------+
| CHARACTER_SET_RESULTS    | latin1            |
| CHARACTER_SET_CONNECTION | latin1            |
| CHARACTER_SET_CLIENT     | latin1            |
| COLLATION_CONNECTION     | latin1_swedish_ci |
+--------------------------+-------------------+
</pre>
</details>

I don't think #405 would work on tux01 for now.

**Comment by BonfaceKilz** [comment]
Fixed. See: https://github.com/genenetwork/genenetwork2/pull/405
