### ISSUE TITLE
Chore(javascript/css): Remove google CDNs and analytics

### ISSUE THREAD

**Issue by BonfaceKilz** [genenetwork/genenetwork2#396]
#### Description

Doing `grep -r google` gets:

<details>
<summary>
Click to see output
</summary>
<pre>
Binary file webtests/chromedriver matches
wqflask/wqflask/templates/new_security/login_user.html:    
wqflask/wqflask/templates/new_security/verification_still_needed.html:    
wqflask/wqflask/templates/new_security/forgot_password.html:    
wqflask/wqflask/templates/new_security/password_reset.html:    
wqflask/wqflask/templates/new_security/forgot_password_step2.html:    
wqflask/wqflask/templates/new_security/register_user.html:    
wqflask/wqflask/templates/new_security/registered.html:    
wqflask/wqflask/templates/new_security/thank_you.html:    
wqflask/wqflask/templates/base.html:    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
wqflask/wqflask/templates/base.html:    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.9.1/jquery-ui.min.js" type="text/javascript"></script>
wqflask/wqflask/templates/loading.html:<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
wqflask/wqflask/templates/reference.html: <A HREF="https://scholar.google.com/scholar?as_q=&as_epq=&as_oq=webqtl+%22genenetwork%22&as_eq=&as_occt=any&as_sauthors=&as_publication=&as_ylo=&as_yhi=&btnG=&hl=en&as_sdt=0%2C5"target="_blank" class="fwn">Google Scholar</A> search for  <I> "genenetwork" OR "webqtl"  </I> generated:
wqflask/wqflask/templates/reference.html:<A HREF="https://scholar.google.com/scholar?as_q=&as_epq=&as_oq=genenetwork.org&as_eq=&as_occt=any&as_sauthors=&as_publication=&as_ylo=&as_yhi=&btnG=&hl=en&as_sdt=0%2C5"target="_blank" class="fwn">Google Scholar</A> search for  <I> "genenetwork.org" </I> generated:
wqflask/wqflask/templates/reference.html:<A href="http://www.sciencedirect.com/science?_ob=ArticleURL&_udi=B6WN5-4VVXSVN-2&_user=10&_rdoc=1&_fmt=&_orig=search&_sort=d&_docanchor=&view=c&_searchStrId=1065487428&_rerunOrigin=google&_acct=C000050221&_version=1&_urlVersion=0&_userid=10&md5=df0a2763fb94c714825793af492de045" target="_blank" class="fwn"><I>Full Text HTML Version</I></A>
wqflask/wqflask/templates/reference.html:Benhamou JP, Rizzetto M, Reichen J, Rodés J (<a href="http://books.google.com/books?id=taE276KCyecC&dq=genenetwork+webqtl"  target="_blank" class="fwn">2007</a>) Textbook of hepatology: from basic science to clinical practice. Blackwell Publishing, p. <a href="http://books.google.com/books?id=taE276KCyecC&pg=PA379&lpg=PA379&dq=genenetwork+webqtl&source=web&ots=2CjGbbDh3B&sig=tXdbQ7KAGOyxOee9TECF40GXyywl"  target="_blank" class="fwn">379</a>), ISBN 1405127414
wqflask/wqflask/templates/reference.html:<a href="http://books.google.com/books?id=ZNYE-FcvYloC&pg=PA102&lpg=PA102&dq=genenetwork+webqtl&source=web&ots=q3RfjmnLjt&sig=sDjpfmvzdx2lKigtJKqbb-H8Di8&hl=en&sa=X&oi=book_result&resnum=3&ct=result#PPA95,M1"  target="_blank" class="fwn">95-114</a>), ISBN 1405127414
wqflask/wqflask/templates/reference.html:Fox JG, Barthold SW, Davisson MT, Newcomer CE (<a href="http://books.google.com/books?id=vnRpW-gI9JMC"  target="_blank" class="fwn">2007</a>) The mouse in biomedical research. (2nd ed). Academic Press,  p. 530.
wqflask/wqflask/templates/reference.html:Hsu HC, Lu L, Yi N, Van Zant G, Williams RW, Mountz JD (<a href="http://books.google.com/books?id=fbTsCdQv7cEC&dq=genenetwork+webqtl&source=gbs_summary_s&cad=0"  target="_blank" class="fwn">2007</a>) Quantitative trait locus mapping in aging systems. In: Methods in Molecular Biology (Vol 371). Biological Aging: Methods and Protocols, ed Tollefsbol TO, Humana Press, Inc., Netlibrary, Springer   
wqflask/wqflask/templates/reference.html:<A href="http://books.google.com/books?id=fbTsCdQv7cEC&pg=RA4-PA332&lpg=RA4-PA332&dq=genenetwork+webqtl&source=web&ots=PawLDYAUam&sig=hOHsKDfumr3U-ZEUtT7Ag6gJAYg&hl=en&sa=X&oi=book_result&resnum=9&ct=result#PRA4-PA321,M1"  target="_blank" class="fwn"><I>Google Book Search</I></A>
wqflask/wqflask/templates/reference.html:Jones BC and Mormede JP (2007) Neurobehavioral genetics: methods and applications. (<a href="http://books.google.com/books?id=P85FPhRKFVMC&pg=PA102&lpg=PA102&dq=genenetwork+webqtl&source=web&ots=-qg3S-C0xQ&sig=HoOCQpZrV3i45I0vPfDb3PfDMvY"  target="_blank" class="fwn">2007</a>)" CRC Press, Taylor & Francis Group, Boca Raton, Florida, p. 102, ISBN 084931903X
wqflask/wqflask/static/new/js_external/chroma.js:      http://code.google.com/p/figue/source/browse/trunk/figue.js#336
wqflask/wqflask/static/packages/pragmaticly-smart-time-ago-40fa376/test/lib/jquery.js:			// http://code.google.com/p/v8/issues/detail?id=1050
wqflask/wqflask/static/packages/colorbox/README.md:  Example: $('a[href='http://msn.com']).colorbox({'href':'http://google.com', iframe:true});
wqflask/wqflask/static/packages/colorbox/example3/index.html:		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
wqflask/wqflask/static/packages/colorbox/example1/index.html:		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
wqflask/wqflask/static/packages/colorbox/example5/index.html:		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
wqflask/wqflask/static/packages/colorbox/example2/index.html:		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
wqflask/wqflask/static/packages/colorbox/example4/index.html:		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

</pre>
</details>

and doing `curl http://gn2.genenetwork.org/ | grep google` gets:

<details>
<summary>
Click to see output
</summary>
<pre>
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 31823  100 31823    0     0  23891      0  0:00:01  0:00:01 --:--:-- 23891
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.9.1/jquery-ui.min.js" type="text/javascript"></script>
</pre>
</details>
</details>

We need to remove the jquery version, and package them in guix and use the ones from there.

**Comment by pjotrp** [comment]
Yes!
