### ISSUE TITLE
Bug: Unable to open new tab for mapping/ correlations with Chrome

### ISSUE THREAD

**Issue by BonfaceKilz** [genenetwork/genenetwork2#399]
#### Description

Based off #394. I'd need to spec this further later

**Comment by fredmanglis** [comment]
Migrated to the [gemtext issue tracker](https://github.com/genenetwork/gn-gemtext-threads/blob/main/issues/unable-to-open-new-tabs-for-mapping-correlations-in-chrome.gmi)
