### ISSUE TITLE
Samples not separated by group on Trait page

### ISSUE THREAD

**Issue by zsloan** [genenetwork/genenetwork2#4]
_From @zsloan on May 5, 2015 18:33_

For example, the BXD strains are not separated from the MDP strains in the strain values portion of the page. I feel like this used to work at some point, though ideally the user would be able to customize which sets of strains he/she wants to use.

_Copied from original issue: zsloan/genenetwork2#10_

**Comment by zsloan** [comment]
_From @lomereiter on May 6, 2015 17:45_

Could you please elaborate on the example?
This code suggests that the groups _are_ separated: https://github.com/zsloan/genenetwork2/blob/master/wqflask/wqflask/templates/show_trait_edit_data.html#L77

**Comment by zsloan** [comment]
I think the issue is that, for whatever reason, the groups aren't being
stored correctly in sample_groups. I think that this is probably related to
the code in show_trait.py, specifically the function "make_sample_lists".

**Comment by zsloan** [comment]
_From @lomereiter on May 7, 2015 9:51_

OK, what is the URL query string to reproduce this bug?

**Comment by zsloan** [comment]
http://gn2.genenetwork.org/show_trait?trait_id=1436869_at&dataset=HC_M2_0606_P

For all BXD data sets, for example, the BXD strains should be separated
from the other non-BXD strains, but they aren't.

**Comment by lomereiter** [comment]
Fixed in https://github.com/lomereiter/genenetwork2/commit/15fa73bf1de40a6f1c8f1866e8c691b2842abdd9

**Comment by pjotrp** [comment]
Reopen if it comes up again.
