### ISSUE TITLE
Suggestion:Fix: Mixed content is not blocked warning from browser

### ISSUE THREAD

**Issue by BonfaceKilz** [genenetwork/genenetwork2#406]
#### Description

We have to "trust" the site:

![Screenshot_2020-07-13_19-09-39](https://user-images.githubusercontent.com/11820306/87327360-a7ac0680-c53c-11ea-918a-b770c0a24c7a.png)

And then later we have:

<img src="https://user-media-prod-cdn.itsre-sumo.mozilla.net/uploads/gallery/images/2015-10-21-18-54-26-fe01d6.png"/> A gray padlock with an orange or yellow triangle as opposed to <img src="https://user-media-prod-cdn.itsre-sumo.mozilla.net/uploads/gallery/images/2019-10-06-15-47-18-7b49e3.png" /> a completely gray button is displayed on the browser(firefox). On chrome, it shows the label "insecure" at the address bar. Well this is caused by the above or by [mixing content](https://support.mozilla.org/en-US/kb/mixed-content-blocking-firefox?redirectlocale=en-US&as=u&redirectslug=how-does-content-isnt-secure-affect-my-safety) but would need further investigation as it may grow into a more annoying problem.

**Comment by zsloan** [comment]
Could this have anything to do with it being https but having references to
http in imports, etc?

**Comment by BonfaceKilz** [comment]
I'm not really sure whether the certs for the domain gn2 are correct.
This will need more exploration. My idea is to worry about this issue
after the python3 migration; but in the meantime if I come up with any
ideas I'll post them here.

-- 
Bonface M. K. (https://www.bonfacemunyoki.com)
One Divine Emacs To Rule Them All
GPG key = D4F09EB110177E03C28E2FE1F5BBAE1E0392253F

**Comment by pjotrp** [comment]
How are we on this issue? Certificates should be fine.

**Comment by BonfaceKilz** [comment]
Yeah. We have this fixed. I reckon the moving js/ css libs to guix resolved this. Now it's safe to redirect http traffic to https. Since this is no longer an issue, I'm going ahead to close it.
