### ISSUE TITLE
Global search does not close connections properly (and is slow)

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#418]
Global search '*' causes loads of aborted connections... I mean

      2020-08-15  2:53:58 140273206434560 [Warning] Aborted connection 45219 to db: 'db_webqtl' user: 'webqtlout' host: '127.0.0.1' (CLOSE_CONNECTION)

generating 6Mb of log file info ...

**Comment by pjotrp** [comment]
In fact, every row in the table has a SQL query that does not close the connection properly.

**Comment by fredmanglis** [comment]
Migrated to the [gemtext issue tracker](https://github.com/genenetwork/gn-gemtext-threads/blob/main/issues/global-search-connection-slow.gmi)
