### ISSUE TITLE
RIF Search seems to return the wrong (different from GN1 results and is slow)

### ISSUE THREAD

**Issue by zsloan** [genenetwork/genenetwork2#42]
A search for "RIF=mitochondrial" in the "Hippocampus Consortium M430v2 (Jun06) PDNN" data set returns over 7000 results in GN2 while it only returns over 3000 in GN1, and it also seems to take 2-3 times as long to run. 

While I wrote the original code, I think it might be best for Lei to take a look at this since he is better with writing queries.

**Comment by lomereiter** [comment]
GN1 uses the `distinct` keyword when doing `ProbeSet` queries (https://github.com/genenetwork/genenetwork/blob/3b7e5fdd08eff75369f05b9a36e39c47a7b379e1/web/webqtl/search/SearchResultPage.py#L582-L587) whereas GN2 currently does not (https://github.com/genenetwork/genenetwork2/blob/f792574e8e07e684ec7501d7be7f4d2736a3b1cc/wqflask/wqflask/do_search.py#L84-L90).

Experimenting in MySQL console confirmed that the difference lies in this, and I'm getting even more results than 7000 without using `distinct`. Running time is about the same, though:
```mysql
MySQL [db_webqtl]> SELECT count(*) from (SELECT ProbeSet.Name as TNAME,  0 as thistable,  ProbeSetXRef.Mean as TMEAN,  ProbeSetXRef.LRS as TLRS, ProbeSetXRef.PVALUE as TPVALUE,  ProbeSet.Chr_num as TCHR_NUM,  ProbeSet.Mb as TMB, ProbeSet.Symbol as TSYMBOL,  ProbeSet.name_num as TNAME_NUM FROM ProbeSetXRef, ProbeSet , GeneRIF_BASIC   WHERE ( ProbeSet.symbol = GeneRIF_BASIC.symbol and       MATCH (GeneRIF_BASIC.comment) AGAINST ('+mitochondrial' IN BOOLEAN MODE))    and ProbeSet.Id = ProbeSetXRef.ProbeSetId   and ProbeSetXRef.ProbeSetFreezeId = 112) A;
+----------+
| count(*) |
+----------+
|    13849 |
+----------+
1 row in set (5 min 5.32 sec)

MySQL [db_webqtl]> SELECT count(*) from (SELECT DISTINCT ProbeSet.Name as TNAME,  0 as thistable,  ProbeSetXRef.Mean as TMEAN,  ProbeSetXRef.LRS as TLRS, ProbeSetXRef.PVALUE as TPVALUE,  ProbeSet.Chr_num as TCHR_NUM,  ProbeSet.Mb as TMB, ProbeSet.Symbol as TSYMBOL,  ProbeSet.name_num as TNAME_NUM FROM ProbeSetXRef, ProbeSet , GeneRIF_BASIC   WHERE ( ProbeSet.symbol = GeneRIF_BASIC.symbol and       MATCH (GeneRIF_BASIC.comment) AGAINST ('+mitochondrial' IN BOOLEAN MODE))    and ProbeSet.Id = ProbeSetXRef.ProbeSetId   and ProbeSetXRef.ProbeSetFreezeId = 112) A;
+----------+
| count(*) |
+----------+
|     3144 |
+----------+
1 row in set (5 min 33.44 sec)
```

**Comment by zsloan** [comment]
While this is definitely a change that needs to be made, it doesn't seem to be the only problem with the GeneRIF search. There are some records that are showing up in the GN2 results but not in the GN1 results, even though there are fewer results overall in GN2 after adding "distinct" to the query. For example, trait 1415759_a_at only shows up in the GN2 results for RIF=mitochondrial with the Hippocampus Consortium M430v2 (Jun06) PDNN data set, despite there being 2215 results for GN2 and 3148 for GN1.

**Comment by zsloan** [comment]
Apparently this issue was actually tripled, not duplicated! I missed the existing issues because I was only looking at the GN2LIVE milestone. Closing this since the problem has changed and the new issue I created better describes it.
