### ISSUE TITLE
Search terms that apply to multiple data set types only work for one data set type

### ISSUE THREAD

**Issue by zsloan** [genenetwork/genenetwork2#43]
The relevant file for this issue is wqflask/wqflask/do_search.py

For example, the LRS search (for example "LRS=(23 46)" or "LRS>30") should be usable for both phenotype and mRNA assay data sets.

Currently, each search term's function inherits from a parent class. Right now LrsSearch inherits from MrnaAssaySearch, which means that it only works for mRNA assay data sets. Ideally there would be some way to choose which class to inherit from based on what the data set type is, but I'm not sure how to do this.

**Comment by lomereiter** [comment]
My humble suggestion:
* make `search_types` a two-level dictionary, with a new level corresponding to dataset type
* move `get_from_clause` and `get_where_clause` of LrsSearch to a separate DoSearch child class, say, LrsSearchCommon
* use multiple inheritance to define LrsSearchPublish and LrsSearchMrna classes (if you don't like this approach, replace all inheritance with composition)

**Comment by zsloan** [comment]
Using Artem's advice I've done this for both the Position search and the LRS search and it seems to be working fine.

The next thing to deal with is Cis and Trans LRS searches, though I don't think it will be too difficult to figure out a reasonable way to deal with them.

**Comment by zsloan** [comment]
This seems to be working now for all existing search terms. There's a problem with GO search (the query needs to look at two separate databases, db_webqtl and db_GeneOntology), but that can be fixed later.
