### ISSUE TITLE
[Bug] Reusing phenotype file names

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#438]
**Describe the bug**

When rerunning an analysis for a dataset the phenotype file gets overwritten, e.g.

    /export/local/home/gn2/production/tmp/gn2/gn2/21481_BXDPublish_pheno.txt

This can lead to conflicts when people run the exact same dataset on the website.

**Fix**

Use unique filenames!

**Comment by zsloan** [comment]
Ah, thanks for catching that; most other filenames were randomized but the phenotype one was apparently missed.

**Comment by pjotrp** [comment]
Can we close this?

**Comment by BonfaceKilz** [comment]
Ping @zsloan; but the api I'm working with should resolve this to some extent...

**Comment by zsloan** [comment]
I'll check about this today. It's possible I forgot to do this, but it
wouldn't be difficult at all to do, so it'll be done either way today.

**Comment by BonfaceKilz** [comment]
zsloan <notifications@github.com> writes:

> I'll check about this today. It's possible I forgot to do this, but it
> wouldn't be difficult at all to do, so it'll be done either way today.
>
Thanks!

-- 
Bonface M. K. D4F09EB110177E03C28E2FE1F5BBAE1E0392253F
Humble GNU Emacs User / Bearer of scheme-y parens
Curator: <https://upbookclub.com> / Twitter: @BonfaceKilz

**Comment by zsloan** [comment]
This should be fixed now with https://github.com/genenetwork/genenetwork2/commit/4bd2a3ac8ee7efba0bfb134a3dc9e12b695e15d6
