### ISSUE TITLE
Position Search isn't working

### ISSUE THREAD

**Issue by zsloan** [genenetwork/genenetwork2#45]
Position search, for example "POSITION=(chr1 25 30)", is not working yet. I think that it used to be implemented and working for mRNA Assay data sets but ran into the same problem as I mentioned for the LRS search with it applied to multiple data set types (in this case both Genotype and mRNA Assay). Since @lomereiter seems to think it's okay to create a separate subclass for each data set type, I'll try and implement it that way.

**Comment by robwwilliams** [comment]
Yes, this is a critical search-- e.g., "mb=(chr1 172 174)" or "position=(chr1 172 174)" when searched against an mRNA or protein data set should find all "parent" genes in this interval where chr1 = chromosome 1 and 172 = 172000000 bp on the genome assembly. For mouse we are still using the old mm9 assembly.

**Comment by zsloan** [comment]
I think that I have it working now for the same sort of search string mentioned by Rob, though you can also use just the chromosome number instead of "chr1"; either works okay. It works for both Genotype and mRNA Assay data sets.

Code still needs to be added that gracefully handles the user using nonexistent or mistyped search commands, but that applies to all other search types as well.

**Comment by zsloan** [comment]
Closing this since it seems to be working now.
