### ISSUE TITLE
First CUDA implementation for pylmm

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#46]
CUDA matrix multiplication and transpose are low hanging fruit for pylmm.

**Comment by robwwilliams** [comment]
Great Pjotr. Here is a good comparison of the K40 and K80 Telsas:
http://blog.xcelerit.com/benchmarks-nvidia-tesla-k80-vs-k40-gpu/
12 GB per GPU is a common feature—twice what we have on the K20. K80 should be almost twice as K40 fast if given the right food.

**Comment by robwwilliams** [comment]
Hmm, maybe I am wrong about that:2x Shared Memory and 2x Register File
" K80 increases effective throughput and bandwidth with 2x shared memory and 2x register file compared to the K40" 

http://www.ocf.co.uk/files/pdf/OCF%20NVIDIA%20K80%20Data%20Sheet.pdf

**Comment by pjotrp** [comment]
Dropped in favour of other projects.
