### ISSUE TITLE
Remove all Javascript from source tree that is not original

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#487]
**Describe the bug**

These files should be moved to Guix or Removed:

https://github.com/genenetwork/genenetwork2/tree/testing/wqflask/wqflask/static/new/js_external

**Comment by pjotrp** [comment]
ping

**Comment by BonfaceKilz** [comment]
Pjotr Prins <notifications@github.com> writes:

> ping

Pong. Catching up to e-mails(and videos) now.

Everything should be removed now. I've just merged
the zxvbn and bootstrap stuff.

-- 
Bonface M. K. D4F09EB110177E03C28E2FE1F5BBAE1E0392253F
Humble GNU Emacs User / Bearer of scheme-y parens
Curator: <https://upbookclub.com> / Twitter: @BonfaceKilz

**Comment by fredmanglis** [comment]
@pjotrp @BonfaceKilz is this done? I am closing it as such, but if it is incomplete, either **reopen it here with more notes and I'll migrate it to the gemtext tracker** or **migrate it to the gemtext tracker with the new notes**
