### ISSUE TITLE
Need to remove all uses of cursor for database connection

### ISSUE THREAD

**Issue by zsloan** [genenetwork/genenetwork2#5]
_From @zsloan on March 26, 2015 21:43_

Instead we should use the flask g import and the syntax "g.db.execute(the query)"

_Copied from original issue: zsloan/genenetwork2#2_

**Comment by pjotrp** [comment]
Downgrading as non-critical

**Comment by zsloan** [comment]
All instances of Cursor from within the GN2 code are removed, but there exist a couple in maintenance scripts. I'm not sure if this issue is also referring to those. If it isn't it can be closed, but I'll hold off for now.

**Comment by chfi** [comment]
Let's treat this as done
