### ISSUE TITLE
Graceful handling of errors

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#50]
When we hit an error the webserver should give a friendly message.

**Comment by pjotrp** [comment]
Zach, what do you suggest as an implementation?

I kinda like the rolling logs that come with Travis, for example

  https://travis-ci.org/pjotrp/bioruby/jobs/39045900

They are as informative as the logs themselves, capturing the output
of the running process.

**Comment by zsloan** [comment]
Do you mean something to replace, for example, Internal Service Error pages
with something more informative? I looked at Travis CI and it seems like it
can test builds when you push or pull with git? Is that how we would use it?

**Comment by pjotrp** [comment]
Travis is for testing, indeed. What I meant to show is that it has a capture log which we can use for forked processes. We can look into this when we are together.

**Comment by pjotrp** [comment]
https://mortoray.com/2014/03/04/http-streaming-of-command-output-in-python-flask/
