### ISSUE TITLE
Need to add plink genotype files for other human data sets or remove the mapping methods that use them

### ISSUE THREAD

**Issue by zsloan** [genenetwork/genenetwork2#52]
Currently the plink .bed/.map/.fam files used by rqtl, GEMMA, and pylmm only exist for a couple data sets, so if you try to run these mapping methods on any other data set it will throw an error (or even worse, not throw an error). At the very least, we shouldn't show these mapping methods for data sets that don't have the necessary plink files. Specifically, we should probably replace the code that just says "if human, show these mapping methods" with something that checks if the relevant genotype files exist.

**Comment by pjotrp** [comment]
We are going to remove these propriety data types and replace them with our genotype/phenotype textual format (for processing) and in compressed form (for storage). Note: plink formats are actually a mess - you need to parse a file twice to get the number of matrix rows, for example.

**Comment by pjotrp** [comment]
Related to https://github.com/genenetwork/genenetwork2/issues/25

**Comment by pjotrp** [comment]
Currently plink and ped files are used - but not included in gn2_data dirs. Needs a solution.
