### ISSUE TITLE
Feature that warns the user of outliers before mapping is missing from GN2

### ISSUE THREAD

**Issue by zsloan** [genenetwork/genenetwork2#55]
GN1 has a feature that pops up something warning the user if any outliers exist in the trait's sample/strain data and I believe it will automatically remove them as well. At the very least, we need to add back in the warning. 

While this feature exists in GN1, the pop-up looks a little strange (aesthetically) so it might be a better idea to not borrow all the code.

**Comment by pjotrp** [comment]
I don't think we should use popups. I prefer the red warning textbox on top of the page or next to the search box. So people can search/run again without closing windows.

**Comment by zsloan** [comment]
This feature was added; warning text appears below the submit button if there's an outlier.
