### ISSUE TITLE
Create list of cool GN1 features that ought to go to GN2

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#56]
Hi Lei,

We need a list of the 10 top features that do not exist in GN2 but should go there at some point. Can you list them here? They wil also go into the GN1 paper.

Pj.

**Comment by robwwilliams** [comment]
Dear Pjotr,

Here is by Top Ten list

1 to 10.  All of the tools that are at the top of any Trait Collection page
in GN1.  Some of these are simply API links to other services (such as GO
analysis using the Gene Set tool. Others are actually useful GN1 code
modules (e.g. Graph, Matrix, Partial, Compare, and Heat Map). :

1. Partial correlation

2. Network graphs

3. Correlation matrices along with simple PCA analysis

[image: Inline image 3]

Minor (I think)

11. Index columns for all tables that when selected also "color" highlight
lines (trivial, I know, but this is hugely useful when screening large
tables). Our GN2 search result and correlation tables do not yet have index
columns and no way to select traits to add to the shopping cart/Trait
collection.

[image: Inline image 1]

12.. All of the useful links in the Trait Data and Analysis pages on GN1.

Add, Find, Verify, GeneWiki, SNPs, and Edit are all useful. Most of these
are just links but Find and GeneWiki, and SNPs are serious efforts that we
can prioritize as you think best.



[image: Inline image 2]




On Thu, May 21, 2015 at 2:43 PM, Pjotr Prins <notifications@github.com>
wrote:

> Hi Lei,
>
> We need a list of the 10 top features that do not exist in GN2 but should
> go there at some point. Can you list them here? They wil also go into the
> GN1 paper.
>
> Pj.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/genenetwork/genenetwork2/issues/56>.
>



-- 
Rob

Robert W. Williams, Ph.D.
UT-ORNL Governor's Chair in Computational Genomics
Chair, Department of Genetics, Genomics and Informatics
University of Tennessee Health Science Center
855 Monroe Avenue, Memphis TN 38163 USA

Office 901 448-7018  CELL 901 604-4752
Office: 501 Wittenborg Building
EMAIL: rwilliams@uthsc.edu
Alternative email: labwilliams@gmail.com
SKYPE: robwwilliams
