### ISSUE TITLE
Add 'personalization' for G2

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#57]
We want to deploy GN2 with other institutes. This means they must be able to put up their own logo and other personalization features by specifying them in settings.py.

**Comment by robwwilliams** [comment]
Yes, definitely. We used to do this even for GN1..

On Thu, May 21, 2015 at 2:46 PM, Pjotr Prins <notifications@github.com>
wrote:

> We want to deploy GN2 with other institutes. This means they must be able
> to put up their own logo and other personalization features by specifying
> them in settings.py.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/genenetwork/genenetwork2/issues/57>.
>



-- 
Rob

Robert W. Williams, Ph.D.
UT-ORNL Governor's Chair in Computational Genomics
Chair, Department of Genetics, Genomics and Informatics
University of Tennessee Health Science Center
855 Monroe Avenue, Memphis TN 38163 USA

Office 901 448-7018  CELL 901 604-4752
Office: 501 Wittenborg Building
EMAIL: rwilliams@uthsc.edu
Alternative email: labwilliams@gmail.com
SKYPE: robwwilliams

**Comment by pjotrp** [comment]
Closed for now.
