### ISSUE TITLE
Gene Network Submit Trait under the Intro menu broken

### ISSUE THREAD

**Issue by eldoyle** [genenetwork/genenetwork2#573]
The link to the Submit Trait webpage http://www.genenetwork.org/submit_trait is resulting in an error.  An image of the error screen is attached and the error message is included below.  The link was working properly last week when I used it previously.  The error occurs either when entering the link directly into a browser as a URL or when navigating to the page through the GeneNetwork Intro menu from other GeneNetwork pages.  I have recreated the error both on Chrome and Firefox.
<img width="645" alt="GeneNetworkError" src="https://user-images.githubusercontent.com/16582740/117230074-da7ffd80-ade1-11eb-85db-0b539348f53c.PNG">

GeneNetwork tux01:gene:2.11-rc2-testing-2770bb20b http://www.genenetwork.org/submit_trait ( 1:32AM UTC May 06, 2021)
    'NoneType' object has no attribute 'get' (error)
      File "/export/local/home/gn2/production/gene/wqflask/utility/helper_functions.py", line 64, in get_species_groups
        if _menu.get(species):

**Comment by squirrelB** [comment]
Yes, it's still broken. Getting the same error message

**Comment by zsloan** [comment]
This should be fixed now; this was apparently introduced by a recent change.

**Comment by fredmanglis** [comment]
Closing this issue as fixed
