### ISSUE TITLE
Variant Browser seems to be using mm9

### ISSUE THREAD

**Issue by rupertoverall** [genenetwork/genenetwork2#581]
When looking for SNPs in GN2, the gene annotations (and, I think, the SNPs) of the results do not match the query.
Searching for a gene gives correct coordinates in the search box at [http://www.genenetwork.org/snp_browser](http://www.genenetwork.org/snp_browser?first_run=true&chosen_strains_mouse=C57BL%2F6J%2CDBA%2F2J%2CA%2FJ%2C129S1%2FSvImJ%2CNOD%2FShiLtJ%2CNZO%2FHlLtJ%2CWSB%2FEiJ%2CPWK%2FPhJ%2CCAST%2FEiJ&chosen_strains_rat=BN%2CF344%2CWLI%2CWMI&variant=SNP&species=Mouse&gene_name=Snx6&chr=19&start_mb=30.1&end_mb=30.12&strains=129P2%2FOlaHsd&limit_strains=on&domain=All&function=All&source=All&criteria=%3E%3D&score=0.0&diff_alleles=on), but the results are for the same coordinates in mm9 (see screenshot).

The example is for a search for 'Snx6' (chr12 54.746356 - 54.795662).

<img width="1068" alt="Screenshot 2021-05-26 at 16 43 43" src="https://user-images.githubusercontent.com/35666678/119680694-b6906480-be41-11eb-9070-9f4c2dffb499.png">

**Comment by pjotrp** [comment]
Interesting. Maybe @acenteno or @robwwilliams can comment.

**Comment by fredmanglis** [comment]
Migrated to [gemtext issue tracker](https://github.com/genenetwork/gn-gemtext-threads/blob/main/issues/variant-browser-using-mm9.gmi)
