### ISSUE TITLE
No able to add to collection

### ISSUE THREAD

**Issue by squirrelB** [genenetwork/genenetwork2#582]
Hi,
Not able to add to collection. This error message
<img width="1295" alt="Screen Shot 2021-05-28 at 1 00 32 PM" src="https://user-images.githubusercontent.com/31778385/120024489-e744db00-bfb4-11eb-8990-dd93f17f0980.png">

**Comment by zsloan** [comment]
This should be fixed now with afc7a742da58a318c2b9c8b1c93209fc3820009a

**Comment by BonfaceKilz** [comment]
Fixed in: https://github.com/genenetwork/genenetwork2/commit/afc7a742da58a318c2b9c8b1c93209fc3820009a
