### ISSUE TITLE
Need a histogram to go with permutation mapping results

### ISSUE THREAD

**Issue by zsloan** [genenetwork/genenetwork2#61]
The way we get the permutation data may differ by the mapping method, but at the very least we should be able to do that for pyLMM since it's our own code (and I'm pretty sure rqtl also returns those results).

Also we should use the same library Artem used if it can be used for histograms as well as regular bar charts, just for the sake of keeping a consistent style.

**Comment by pjotrp** [comment]
Should also be done for the other tools (pylmm can be done later).

**Comment by zsloan** [comment]
The histogram from GN1 was added to mapping results a while back.
