### ISSUE TITLE
Need to remove mapping methods when necessary genotype files don't exist

### ISSUE THREAD

**Issue by zsloan** [genenetwork/genenetwork2#62]
This is related to the other issue I created to remove Interval Mapping for human traits. In general, we need to remove the option to use mapping methods for data sets that don't have a necessary genotype file; right now the user will receive an error (or worse, nothing at all) if they use a method and the correct file doesn't exist.

I put this in the GN2 LIVE milestone because we don't want users to get errors when they try and run our mapping tools.

**Comment by zsloan** [comment]
While I've written the code that correctly checks for the genotype files, the problem is that there are many "dummy" .geno files that seem to be used only to get the list of sample names. As a result, checking for these files alone is not sufficient. I think that as a stopgap we should just not show the mapping methods that require .geno files for all human data sets, since no human data sets seem to have non-dummy .geno files (their genotype data is stored in the plink files - .bim, .map, etc).

**Comment by zsloan** [comment]
I'm changing the milestone to GN2 LATER since this has been dealt with in a way that is sufficient for going live. Later, we can either remove the dummy .geno files and change the way we get sample lists or add relevant mapping methods as metadata in the database.

**Comment by pjotrp** [comment]
@zsloan should we close this one?

**Comment by zsloan** [comment]
Yeah; we now have a mapping method ID in the database that shows which methods are applicable to a particular group.
