### ISSUE TITLE
New error in genenetwork.org when performing correlations

### ISSUE THREAD

**Issue by Menzieslab** [genenetwork/genenetwork2#628]
I have been trying to perform correlations on the newer version of genenetwork.org and since the weekend have been receiving errors for all of my analyses. Here is an example:
 
I tried to examine the top 500 gene correlations for Hnf4a (10478389) in its own dataset: EPFL/LISP BXD CD Liver Affy Mouse Gene 1.0 ST (Aug18) RMA  which resulted in an error. Here is the “full stack trace”:

GeneNetwork tux01:gene:2.11-rc2-latest_20211018-26949f576  http://www.genenetwork.org/corr_compute ( 2:42AM UTC Nov 16, 2021)  ['Traceback (most recent call last):', '  File "/usr/local/guix-profiles/gn-latest-20211105-slow/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request', '    rv = self.dispatch_request()', '  File "/usr/local/guix-profiles/gn-latest-20211105-slow/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request', '    return self.view_functions[rule.endpoint](**req.view_args)', '  File "/export/local/home/gn2/production/gene/wqflask/wqflask/views.py", line 933, in corr_compute_page', '    correlation_results = compute_correlation(request.form, compute_all=True)', '  File "/export/local/home/gn2/production/gene/wqflask/wqflask/correlation/correlation_gn3_api.py", line 188, in compute_correlation', '    (this_trait_data, target_dataset_data) = fetch_sample_data(', '  File "/export/local/home/gn2/production/gene/wqflask/wqflask/correlation/correlation_gn3_api.py", line 153, in fetch_sample_data', '    target_dataset.get_trait_data(list(sample_data.keys()))', '  File "/export/local/home/gn2/production/gene/wqflask/base/data_set.py", line 803, in get_trait_data', '    cache_dataset_results(', '  File "/export/local/home/gn2/production/gene/wqflask/base/data_set.py", line 1289, in cache_dataset_results', '    table_timestamp = query_table_timestamp(dataset_type)', '  File "/export/local/home/gn2/production/gene/wqflask/base/data_set.py", line 1271, in query_table_timestamp', '    date_time_obj = g.db.execute(query_update_time).fetchone()[0]', "TypeError: 'NoneType' object is not subscriptable"]

**Comment by Alexanderlacuna** [comment]
thanks for reporting the issue. The bug is now fixed.
