### ISSUE TITLE
Global search does not return results

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#629]
**Describe the bug**

Try a search for `Brca2`

I am trying to add an example to this storyboard:

https://github.com/genenetwork/gn-docs/blob/master/story-boards/starting-from-known-gene.md#use-the-search-page

**Comment by pjotrp** [comment]
Interestingly luna does no better:

http://luna.genenetwork.org/gsearch?type=gene&terms=brca2

**Comment by fredmanglis** [comment]
Migrated to [gemtext tracker](https://github.com/genenetwork/gn-gemtext-threads/blob/main/issues/global-search-results.gmi)
