### ISSUE TITLE
Add log transform option

### ISSUE THREAD

**Issue by zsloan** [genenetwork/genenetwork2#65]
A user has informed me that it would be useful to be able to log transform trait data on the fly. The option could just be in the same general area as the "Block samples" options. I imagine that this would be be pretty easy to do, though it isn't high priority.

Rob says that we should check for several things when doing the log transform:
- Check for 0's and if so add 1 and inform user (this might be a bad idea if all values between 0 and 1)
- If negative numbers, then can't log

**Comment by chfi** [comment]
Trello if still relevant
