### ISSUE TITLE
Parental strains showing up in separate group for some data sets

### ISSUE THREAD

**Issue by zsloan** [genenetwork/genenetwork2#69]
Here is an example: http://gn2_zach.genenetwork.org/show_trait?trait_id=13&dataset=C57BL-6JxC57BL-6NJF2Publish

My guess is that this only occurs for data sets that only have one "group" of strains/samples. It is probably related to the change Artem did that had fixed strain/sample groups for data sets that have multiple strain/sample groups, so I'm tagging him on this.

**Comment by lomereiter** [comment]
This is actually competely unrelated to my changes.

I found that there's a missing line in webqtlUtil.py that was added in GN1 quite a while ago (https://github.com/genenetwork/genenetwork/commit/40d1f4bc2e91a280e88d006eaec3d2f5d2d9eb90):
 ```python
'C57BL-6JxC57BL-6NJF2':['', '', 'C57BL/6J', 'C57BL/6NJ'],
```
However, the current GN2 code dies with `TypeError: can only concatenate list (not "NoneType") to list`, apparently expecting F1 and F2 to be non-empty.
