### ISSUE TITLE
Embed a (mapped) QTL genome browser

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#79]
We need a canvas based fast genome browser that can display mapped QTL as well as other features
and genome tracks. One candidate is JBrowse.

**Comment by pjotrp** [comment]
To view a QTL map go to http://www.genenetwork.org/ and chose, for example, Mouse - BXD - Bone Femur mRNA - and the combined search 'MEAN=(15 16) LRS=(23 46)'. Click on a record and select mapping tools, Interval mapping and hit 'Compute'.

**Comment by pjotrp** [comment]
In GN2 you can try http://gn2.genenetwork.org/ and choose Brain mRNA, one of the datasets and search for 'LRS=(23 46)'. Click on one of the records and choose one of the mapping tools. This time the QTL browser is a little bit interactive. You can click to zoom in on a chromosome.

**Comment by robwwilliams** [comment]
Good progress. Here are some issues I had:
1. Could not resize the mapping output window
2. Could not figure out how to get back to the whole genome view once I had zoomed into a single chromosome
3. Some inconsistency in loading single chromosome views (I got a blank frame with no LRS function)

**Comment by pjotrp** [comment]
@robwwilliams this issue is related to replacing the QTL browser with a (new) full genome browser. Marjan is evaluating possibilities.
 
Moved your comment to a new issue https://github.com/genenetwork/genenetwork2/issues/82 so it can be treated as a bug.

**Comment by pjotrp** [comment]
Closed for now.
