### ISSUE TITLE
BUG: mapped QTL display

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork2#82]
https://github.com/robwwilliams wrote:

1. Could not resize the mapping output window
2. Could not figure out how to get back to the whole genome view once I had zoomed into a single chromosome
3. Some inconsistency in loading single chromosome views (I got a blank frame with no LRS function)

**Comment by zsloan** [comment]
Regarding the issues:

1. This isn't possible using colorbox and is one of the reasons why I want to make the mapping results open in a new window. 

2. There's a "Return to full view" button above the figure and it seems to work. Let me know if you can think of a better place to put it or another preferred way of returning to the full view.

3. I noticed this issue when using Interval Mapping and just fixed it. Let me know if you see this happening for any other mapping results.
