### ISSUE TITLE
Error when selecting record ID

### ISSUE THREAD

**Issue by kendallaking** [genenetwork/genenetwork2#829]
This is day 2 of encountering this issue. Firstly, when opening the main page of Genenetwork, it is slow to load the select and search categories. It is slow to bring up the record IDs when typing in a gene name, and it won't open any record ID. 

   GeneNetwork tux01:gene:2.11-rc2 
    Expecting value: line 1 column 1 (char 0) (error)

Mouse
BXD Family
Muscle mRNA
[EPFL/LISP BXD CD Muscle Affy Mouse Gene 1.0 ST (Nov12) RMA Exon Level]

Search: t1r2
Record ID: 10509812

**Comment by zsloan** [comment]
Try it again now. I'm still not sure what the issue was, but I restarted the GN3 service (which is what the problem stemmed from) and the trait pages seem to be loading again.

**Comment by kendallaking** [comment]
> Try it again now. I'm still not sure what the issue was, but I restarted the GN3 service (which is what the problem stemmed from) and the trait pages seem to be loading again.

Thank you! It's working and all downstream correlations working too.
