### ISSUE TITLE
Need an error page for wrong search terms

### ISSUE THREAD

**Issue by zsloan** [genenetwork/genenetwork2#86]
Currently you get an ugly Internal Server Error page if you use a search term that doesn't exist. Instead we should have an actual page that tells the user they used a wrong/nonexistent search term.

I've already created a fix for this that is in testing now, so let me know if you still see any errors (or get the error page for something you think that you should be getting results for).

**Comment by lomereiter** [comment]
Genotype search with suggested search terms `MEAN=(15 16)` gives Internal Error:
http://gn2.genenetwork.org/search?species=mouse&group=BXD&type=Genotypes&dataset=BXDGeno&search_terms=MEAN%3D%2815+16%29&FormID=searchResult

**Comment by zsloan** [comment]
I had forgotten to add the template for the search error page, so now it should work correctly.

**Comment by zsloan** [comment]
This seems to be working, so I'll go ahead and close it. Let me know if anyone encounters a bad error page as a result of a search.
