### ISSUE TITLE
rqtl not working for some groups

### ISSUE THREAD

**Issue by zsloan** [genenetwork/genenetwork2#90]
Here is an example trait it doesn't work for: http://gn2_zach.genenetwork.org/show_trait?trait_id=10014&dataset=HLCPublish

The error I'm receiving is:
Error in data.frame(..., check.names = FALSE) :
  arguments imply differing number of rows: 426, 427
In addition: Warning messages:
1: In summary.cross(cross) : Strange genotype pattern.

I'm guessing there's some issue in the genotype file.

**Comment by robwwilliams** [comment]
Yes, R/qtl is not appropriate for Genome-wide association studies of humans. We need database tables that include enough metadata to make it possible for the code to "know" appropriate methods. here are several types of mapping cohorts. All current human cohorts are GWAS (genome-wide association study) cohorts and R/qtl is not the right tool. PLINK and pyLMM and GEMMA are appropriate.

**Comment by zsloan** [comment]
Making this issue was actually kind of a mistake because I did not realize when I made it that I was looking at a human trait. The changes I made that check for the relevant genotype files and (temporarily) bar rqtl/qtlreaper from being used with all human groups fixes this issue (rqtl should longer show up if you open that same link), so I'm going to close this issue.
