### ISSUE TITLE
Cannot clone, pull or push to repository (or a fork) when using LFS enabled GH account

### ISSUE THREAD

**Issue by mamarjan** [genenetwork/genenetwork2#95]
I'm having trouble with this repository. I can't just clone the repository, I have to use --recourse-submodules, but even then the clone is not really usable.

I have contacted GitHub support, given that the errors were related to LFS, and got a response back:

"It doesn't look like the genenetwork organization has Git LFS enabled. Did you transfer that repository to the organization after adding files with Git LFS?"

As anonymous I can clone the repository, but I think that because I have LFS enabled on my own GH account (mamarjan), the git-lfs tool tries to fetch files and fails, then leaves the checkout only halfway done.

A solution would be to either request LFS support for the organization account, or to remove the LFS managed files from the repository.

(Or for me, to get a new GH account.)

**Comment by robwwilliams** [comment]
Dear Marjan,
I hope that Lei and Pjotr can help you with this problem. I will check with
Lei later today.

On Thu, Jul 16, 2015 at 6:46 AM, Marjan Povolni <notifications@github.com>
wrote:

> I'm having trouble with this repository. I can't just clone the
> repository, I have to use --recourse-submodules, but even then the clone is
> not really usable.
>
> I have contacted GitHub support, given that the errors were related to
> LFS, and got a response back:
>
> "It doesn't look like the genenetwork organization has Git LFS enabled.
> Did you transfer that repository to the organization after adding files
> with Git LFS?"
>
> As anonymous I can clone the repository, but I think that because I have
> LFS enabled on my own GH account (mamarjan), the git-lfs tool tries to
> fetch files and fails, then leaves the checkout only halfway done.
>
> A solution would be to either request LFS support for the organization
> account, or to remove the LFS managed files from the repository.
>
> (Or for me, to get a new GH account.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/genenetwork/genenetwork2/issues/95>.
>



-- 
Rob

Robert W. Williams, Ph.D.
UT-ORNL Governor's Chair in Computational Genomics
Chair, Department of Genetics, Genomics and Informatics
University of Tennessee Health Science Center
Room 501
855 Monroe Avenue, Memphis TN 38163 USA

Office 901 448-7018  CELL 901
Office: 501 Wittenborg Building
EMAIL: rwilliams@uthsc.edu
Alternative email: labwilliams@gmail.com
SKYPE: robwwilliams

**Comment by lomereiter** [comment]
I also experience issues when trying to pull the changes, after some `.geno` files were turned into LFS-backed in https://github.com/genenetwork/genenetwork2/commit/83ff8ce678f15f2f6003a5800a75166544d7c6fa

**Comment by lyan6** [comment]
But how to get Git LFS enabled?

https://git-lfs.github.com/

**Comment by lomereiter** [comment]
Write a support request, I guess? (https://github.com/contact)

**Comment by lyan6** [comment]
Hi lomereiter,

I submitted a support request this afternoon.
Thanks.

**Comment by mamarjan** [comment]
Professor,
I was in contact with Pjotr who proposed raising this issue so that Lei could take care of it.

--

Lei,

On the following page there is a link "Sign up for early access":

https://git-lfs.github.com/

Though it took a few weeks for me to get access. Once you  make the request on behalf of genenetwork, I can ask the support person to allow us to get is faster if possible.

**Comment by mamarjan** [comment]
I got a response:

We can get the genenetwork organzation set up with LFS but we're prevented from doing so at the moment because there's no payment method on file.  If you add a payment method in your Billing Settings (https://github.com/organizations/genenetwork/settings/billing) we can get your organization LFS-enabled. You won't be charged unless you upgrade your LFS plan to one of the paid tiers.

If that's something you'd like to do just let us know when you've added the payment method.

Thanks!
Alex

**Comment by mamarjan** [comment]
I have solved my immediate problem by removing the following lines from my ~/.gitconfig file:

[filter "lfs"]
	clean = git lfs clean %f
	smudge = git lfs smudge %f
	required = true

However, this does not solve the underlying problem of having files in the repository which cannot be downloaded by anybody new to the project, or at least that's the impression I got.

**Comment by pjotrp** [comment]
Hi Marjan,

I'll look into it.

Pj.

**Comment by pjotrp** [comment]
Related to https://github.com/genenetwork/genenetwork/issues/28 we are purging LFS from the main repos. LFS is not git (it is a github thing) and therefore unwanted.

**Comment by mamarjan** [comment]
Confirmed that I can clone the repo without issues now. Closing issue.
