### ISSUE TITLE
Hitting enter in the search field creates a new line instead of doing the search

### ISSUE THREAD

**Issue by zsloan** [genenetwork/genenetwork2#98]
I think that this is just because the search field is a text area instead of just a one line high input area. I'm not sure if there's a way to fix this without changing the type of input field.

**Comment by lomereiter** [comment]
https://stackoverflow.com/questions/14711245/how-to-submit-a-form-when-pressing-enter-in-a-textarea

**Comment by sn3twork** [comment]
If these search forms are submitted with empty values (e.g. hitting enter as the first action) an internal server error will be returned.

**Comment by zsloan** [comment]
Thanks, I'll fix this. I guess I missed it because I had mostly tested
searches without using the enter key to submit.

**Comment by sn3twork** [comment]
So you know, i tested this on the live site... and it breaks for double enter due to \n being appended after the first enter press. I'm gonna add in a left/right trim.

**Comment by zsloan** [comment]
I fixed this by just disabling the default behavior for pressing enter. It still submits the search, but doesn't go to a newline before doing so anymore.
